### ISSUE TITLE
RFE: add support for alpha

### ISSUE THREAD

**Issue by jduerstock** [seccomp/libseccomp#105]
The Linux Kernel supports the DEC alpha (alpha) architecture, it would be nice if libseccomp supported this ABI.

Debian/alpha is unofficially supported under Debian ports.  See https://buildd.debian.org/status/fetch.php?pkg=libseccomp&arch=alpha&ver=2.3.1-2.1&stamp=1479504017&raw=0 for the current build log failure.

**Comment by jrtc27** [comment]
This is blocked on kernel support; `arch/alpha/Kconfig` doesn't `select HAVE_ARCH_SECCOMP_FILTER`, likely because one of the requirements is missing.

**Comment by pcmoore** [comment]
Yes, as @jrtc27 already said, we need support in the kernel before we can add support in the library.  I'm not aware of anyone adding support to alpha, are you @jduerstock or @jrtc27?

**Comment by pcmoore** [comment]
While I will always have a soft spot for Alpha, it's unlikely we will ever see a mainstream, modern distro supporting this ABI (or new hardware for that matter) so let's close this issue.  Sorry @jduerstock :/
