### ISSUE TITLE
Release support for SCMP_ACT_KILL_PROCESS

### ISSUE THREAD

**Issue by bobrik** [seccomp/libseccomp#145]
It's been more than a year since the last release:

> libseccomp v2.3.3
> @pcmoore released this on Jan 10, 2018 · 146 commits to master since this release

b2f15f3d02f seems particularly useful:

* https://github.com/systemd/systemd/issues/11967
* https://github.com/golang/go/issues/30753

**Comment by pcmoore** [comment]
We have a GitHub milestone (link below) that has been tracking the upcoming release, you'll note there is only one placeholder issue remaining, which should be addressed later this week.

Since this is not an issue in the traditional sense, I'm going to close this.

**Comment by pcmoore** [comment]
Ooops, I forgot to include the milestone link, here it is:

* https://github.com/seccomp/libseccomp/milestone/2
