### ISSUE TITLE
Q: backport patches from master to release-2.4 for v2.4.2

### ISSUE THREAD

**Issue by pcmoore** [seccomp/libseccomp#161]
We need to collect a list of commits in master to backport to the release-2.4 branch for the v2.4.2 release.

**Comment by pcmoore** [comment]
Candidates:
* 0d73daf07490656130e0f5311ad12ca8818752c5
* 3f214cbbbbd663dd4e7fe90638af4971b436ec00
* d390edad9a8540c2e2dd0b12732cc8dd3fe1cc69
* 5fc22428507ecea00ee9e2215d972777da9a99b6
* 4bec773fb401433bbfbbef111a49e1d2acbc4fcf
* ff7fc73bdf4602323ce320a2094c006c9c3e4d42
* 2b406e3b274407ceef53fa3de9469cfbd0fd0ddb

**Comment by drakenclimber** [comment]
0d73daf - Agreed
3f214cb - Agreed
d390eda - Agreed
5fc2242 - Agreed
4bec773 - Agreed
ff7fc73 - Agreed
2b406e3 - Agreed

I don't remember the details of this commit - 3570b5cf9acbd1711d417e08ec608eea7b83d416.  Do we need to backport it?

**Comment by pcmoore** [comment]
> I don't remember the details of this commit - 3570b5c. Do we need to backport it?

The release-2.4 branch includes the SECCOMP_FILTER_FLAG_LOG/log_enable attribute so we need to make sure we reset it properly.  The SPEC_ALLOW/spec_allow attribute isn't in the release-2.4 branch so that will need to be dropped, but that is pretty trivial.

**Comment by pcmoore** [comment]
As a test of your new write access @drakenclimber, do you want to backport these patches and put together a PR for the release-2.4 branch; I'll give you the ACK (assuming all looks good), and you can do the commit?

As an aside, backports are simple, just cherry-pick the patches from the master branch (if you are using stgit, it's the `stg pick` command) and make note of any edits necessary.  If you've got any questions, or run into any problems let me know.

**Comment by drakenclimber** [comment]
Sure.  I can give it a shot.

**Comment by drakenclimber** [comment]
Here's the branch with all of the backported commits in it.  I mentioned "Issue #161" in the last commit so that it would automatically connect to this thread.

https://github.com/drakenclimber/libseccomp/tree/issues/161

**Comment by pcmoore** [comment]
Thanks.  Is there a reason not to create a PR for this?

Now that there are two of us, I think sticking with a _slightly_ more formal process is important to keep our (and the tree's) sanity :)

**Comment by drakenclimber** [comment]
> Thanks. Is there a reason not to create a PR for this?

Good call.  I'll make a PR.  It's been a rather long day :(

**Comment by pcmoore** [comment]
Sorry, I spaced earlier on your comment regarding 3570b5cf9acbd1711d417e08ec608eea7b83d416 - good catch on that one, I mistakenly thought it was from the list I put together :/

**Comment by drakenclimber** [comment]
Merged into release-2.4 branch.

https://github.com/seccomp/libseccomp/commit/0f11bb83d92ae74669f4a5e9c240b1e353d5a596
