### ISSUE TITLE
Q: installing seccomp from source does not include version

### ISSUE THREAD

**Issue by GinesGarcia** [seccomp/libseccomp#162]
Hi, 
I'm installing seccomp package from source but checking SCMP_VER_MAJOR/MINOR/MICRO all of them are set to 0. Moreover, when running make install command, it generates libseccomp.so.0.0.0 libseccomp.so.0 files and I was expecting versioning numbers instead of 0s. Should I do something to correctly set those values to the specific version?

Regards,
Ginés.

**Comment by pcmoore** [comment]
You need to run the autogen.sh script first if you are attempting to build/install libseccomp from source.  Taken from the [README.md](https://github.com/seccomp/libseccomp/blob/master/README.md) file in the sources:

> However, if you are building the library from sources retrieved from the source repository you may
> need to run the autogen.sh script before running configure. In both cases, running "./configure -h" will
> display a list of build-time configuration options.

I believe this will solve your problem so I'm going to close this issue now, if you are still running into problems please feel free to reopen this issue.

**Comment by GinesGarcia** [comment]
Hi, 
First of all thanks a lot for the reply. 
I'm still facing that issue :(

These are the steps I followed:
```
make clean
./autogen.sh
./configure
make
make install
```
I was looking at the configure.sh options, but I think there is nothing related to versioning. Do you know what could be the issue?

Thanks,
Ginés.

**Comment by pcmoore** [comment]
Oh, yes, I'm very sorry, I replied with the wrong answer!

The code in the master branch intentionally has the version set to 0.0.0 to avoid conflicts with the released versions; if you want to build from source you will need to manually update the version information like we do for releases.  See commit bd10aab13c7248cc0df57512617e33d6743d33a6 for an example (hint: look for the change to `AC_INIT(...)`).

**Comment by GinesGarcia** [comment]
Thanks a lot!! 
now seccomp has its own version :)

Regards,
Ginés.
