### ISSUE TITLE
RFE: update the syscall list to the latest Linux -rcX release for libseccomp v2.4.2

### ISSUE THREAD

**Issue by pcmoore** [seccomp/libseccomp#163]
We want to make sure we support the latest kernel release.

**Comment by pcmoore** [comment]
Possibly related: #166

**Comment by pcmoore** [comment]
Possibly related: https://github.com/systemd/systemd/pull/13319

**Comment by pcmoore** [comment]
@drakenclimber I'm thinking we may need to bump the priority on this and get an updated release out within the next week or two (complicated slightly by LSS-NA).  What do you think?

**Comment by drakenclimber** [comment]
Yeah, let's talk about this at LSS.  I agree that the priority of a v2.4.2 release is increasing.

**Comment by pcmoore** [comment]
This probably means backporting #176 and likely bf162816a6e42d7a40e54aadc18d1a98c34ca971 to make the backport less ugly.

**Comment by pcmoore** [comment]
@drakenclimber for reasons discussed over email, I'm going to go ahead and assign this to you.  Feel free to reassign to me, or drop it as unassigned if you don't agree.

**Comment by drakenclimber** [comment]
Sounds good.  I'm swamped this week, but I can cherry-pick the commits you cited into a v2.4.2 release early next week.

**Comment by pcmoore** [comment]
Great, thank you.  I'm currently at LSS-EU so my time will be a bit limited this week too; next week will be a bit busy as well, but I should have some time to help out if you get stuck in the release process.

**Comment by drakenclimber** [comment]
I was able to find some time this morning to do the backports.  I created pull request https://github.com/seccomp/libseccomp/pull/179 with the proposed changes

**Comment by pcmoore** [comment]
Since PR #179 has been merged, I think we can close out this issue.
