### ISSUE TITLE
RFE: make cython binary name configurable

### ISSUE THREAD

**Issue by debfx** [seccomp/libseccomp#169]
The binary name for cython is hardcoded in configure.ac to "cython". Unfortunately the Debian package of the Python 3 variant of cython is called "cython3".

It would be great if this could be made configurable, making it easier for the Debian package to switch to Python 3 only.

**Comment by pcmoore** [comment]
Thanks for the report.  I'm guessing we can probably modify configure.ac to first check for "cython3" and if that fails we can fallback to "cython".

With Python 2.x reaching end of life at the end of 2019, I don't see any reason to worry about Python 2.x in libseccomp v2.5.x (and above).

**Comment by pcmoore** [comment]
Travis is currently testing it, but I think the following commit should fix your problem, if you have a chance could you verify that it works for you?
* https://github.com/pcmoore/misc-libseccomp/commit/300296759682801a286316ba8b90a371e68bc8c3

**Comment by debfx** [comment]
Thanks! Yes, it works fine with this commit.

Just a cosmetic issue. This line should also you `$cython` instead of `cython`. Otherwise printing the version is broken.

` 	AS_ECHO("checking cython version... $(cython -V 2>&1 | cut -d' ' -f 3)") `

**Comment by pcmoore** [comment]
> Thanks! Yes, it works fine with this commit.

Great, thanks for the help testing.

> Just a cosmetic issue ...

Good catch!  I'll update the patch and submit a PR.

**Comment by pcmoore** [comment]
See PR #188.

**Comment by pcmoore** [comment]
We've merged PR #188 so I think we can close this out, if you continue to notice any problems using the master branch let us know.

This fix should ship as part of libseccomp v2.5.
