### ISSUE TITLE
BUG: building for mips produces many __NR_cacheflush redefined warnings

### ISSUE THREAD

**Issue by vapier** [seccomp/libseccomp#17]
building in a mips/n32 userland and current git (7f3ae6e6a12390bd38f0787b242f60c47ad076c3):
```
In file included from system.c:26:0:
../include/seccomp.h:1249:0: warning: "__NR_cacheflush" redefined [enabled by default]
 #define __NR_cacheflush  __PNR_cacheflush
 ^
In file included from ../include/seccomp.h:27:0,
                 from system.c:26:
/usr/include/asm/unistd.h:928:0: note: this is the location of the previous definition
 #define __NR_cacheflush   (__NR_Linux + 197)
 ^
```

**Comment by pcmoore** [comment]
Those looks related to the ARM specific syscall fix we applied recently, I'll take a look.

**Comment by pcmoore** [comment]
I believe this should now be fixed with current git, e.g. 099f4214ce4fe5f53cf0f59e96b71bf4d54a8cd6 or later.  Are you able to verify this and report back?

**Comment by vapier** [comment]
building against commit 099f4214ce4fe5f53cf0f59e96b71bf4d54a8cd6 w/linux-4.4 headers yields same result:
```
  CC       libseccomp_la-system.lo
In file included from system.c:26:0:
../include/seccomp.h:1250:0: warning: "__NR_cacheflush" redefined
 #define __NR_cacheflush  __PNR_cacheflush
 ^
In file included from ../include/seccomp.h:27:0,
                 from system.c:26:
/usr/mips64-unknown-linux-gnu/usr/include/asm/unistd.h:934:0: note: this is the location of the previous definition
 #define __NR_cacheflush   (__NR_Linux + 197)
 ^
```

which makes sense as the header still only looks for the ARM-specific define, not the common one:
```
include/seccomp.h.in:
#define __PNR_cacheflush    -10104
#ifdef __ARM_NR_cacheflush                          <<< bad check
#define __NR_cacheflush     __ARM_NR_cacheflush
#else
#define __NR_cacheflush     __PNR_cacheflush
#endif /* __ARM_NR_cacheflush */
```

**Comment by pcmoore** [comment]
Yes, my apologies, I've been looking at the 4.3 x86 stuff for too long and missed the obvious.  I'll get back to you once I have a proper fix.  Thanks for your patience and help testing.

**Comment by pcmoore** [comment]
Okay, let's try this again with 43bc4449e534d09f8233f9d98f12b60d047ead0f.

**Comment by pcmoore** [comment]
@vapier have you had a chance to verify the code in master?

**Comment by vapier** [comment]
sorry, didn't realize you were waiting for me.  current master looks fine.  thanks!

**Comment by pcmoore** [comment]
No worries, I like to get confirmation from the original reporter whenever possible.  Thanks again for your help!
