### ISSUE TITLE
BUG: unable to import python3 bindings in debian based system (Module not found)

### ISSUE THREAD

**Issue by kulkarnisaumitra98** [seccomp/libseccomp#170]
I configured with following flag as mentioned 
./configure --enable-python

**Comment by pcmoore** [comment]
I'm not sure if it is related, but have you seen issue #169?

**Comment by kulkarnisaumitra98** [comment]
I changed the makefile which is generated by replacing the python will python3 , and it worked , i am not sure if its the right way though?

Also after successfully installing I tried to run the simple example given in seccomp.pyx :-

    import sys
    from seccomp import *
    # create a filter object with a default KILL action
    f = SyscallFilter(defaction=KILL)
    # add syscall filter rules to allow certain syscalls
    f.add_rule(ALLOW, "open")
    f.add_rule(ALLOW, "close")
    f.add_rule(ALLOW, "read", Arg(0, EQ, sys.stdin))
    f.add_rule(ALLOW, "write", Arg(0, EQ, sys.stdout))
    f.add_rule(ALLOW, "write", Arg(0, EQ, sys.stderr))
    f.add_rule(ALLOW, "rt_sigreturn")
    # load the filter into the kernel
    f.load()

But I ended up getting this error

f.add_rule(ALLOW, "read", Arg(0, EQ, sys.stdin))
  File "seccomp.pyx", line 342, in seccomp.Arg.__cinit__
TypeError: an integer is required

I tried to figure it out but couldn't solve it.

**Comment by pcmoore** [comment]
> I changed the makefile which is generated by replacing the python will python3 , and it worked , i am not sure if its the right way though?

Glad this worked.  This likely means we need to change how we call Python in a similar way to how we are going to fix the Cython problem in issue #169.

> Also after successfully installing I tried to run the simple example given in seccomp.pyx ...

Did you try running the python tests?  Did those work?

```
# cd tests
# ./regression -m python
```

**Comment by kulkarnisaumitra98** [comment]
Yes I ran the tests successfully with no failed test.

The TypeError issue was solved by changing the sys.stdin, sys.stdout and sys.stderr argument of the Arg constructor , since I guess the datum_a value expected was of type interger and the type of sys.stdin is file , so changing the values with the default file descriptors seem to solve the issue.

Everything seems to work allright now :+1:  , for both python2.x and python3.x as well.

**Comment by pcmoore** [comment]
Great, thanks!

**Comment by pcmoore** [comment]
Travis is currently testing it, but I think the following commit should fix your problem, if you have a chance could you verify that it works for you?
* https://github.com/pcmoore/misc-libseccomp/commit/300296759682801a286316ba8b90a371e68bc8c3

**Comment by pcmoore** [comment]
See PR #188.

**Comment by pcmoore** [comment]
We've merged PR #188 so I think we can close this out, if you continue to notice any problems using the master branch let us know.

This fix should ship as part of libseccomp v2.5.
