### ISSUE TITLE
Q: libseccomp spec file for v2.3.3 to build on s390x RHEL

### ISSUE THREAD

**Issue by AnitaNayak** [seccomp/libseccomp#171]
I want to build the libseccomp rpm on s390x on RHEL. But I am not finding the corresponding spec file. Can anyone please guide on this to get the spec file and to build the rpm.
Thank you.

**Comment by pcmoore** [comment]
We are focused on upstream libseccomp and don't generally provide distro specific support and/or packages.  You should contact Red Hat support for help regarding the RHEL libseccomp package.
