### ISSUE TITLE
Q: Install libseccomp on OS X

### ISSUE THREAD

**Issue by erdumbledore** [seccomp/libseccomp#173]
I am trying to install libseccomp on osx. libseccomp is a dependency for a [code evaluation software](https://github.com/QingdaoU/Judger/) that I am tyring to install. I am unable to install/build libseccomp on osx. I get errors for missing dependencies - first got missing `endian.h`; fixed it but then got missing `elf.h`; fixed it but then got missing `elftypes.h`.
I think I am not building the repo in a proper way. Is there any doc on how to build/install the repo on osx ?

OS details:
macOS Mojave - 10.14.5
Have already install xcode

**Comment by roryrjb** [comment]
@erdumbledore [seccomp](https://en.wikipedia.org/wiki/Seccomp) is a Linux specific technology that requires the Linux kernel. If you need this on OSX then you'll need to use virtualisation. Perhaps Docker on OSX would make this pretty straightforward for your project.

**Comment by pcmoore** [comment]
As @roryrjb already said, libseccomp relies on functionality that is currently only present in the Linux Kernel; other OSes, such as OS X, will not work.

Closing this issue.

**Comment by erdumbledore** [comment]
> @erdumbledore [seccomp](https://en.wikipedia.org/wiki/Seccomp) is a Linux specific technology that requires the Linux kernel. If you need this on OSX then you'll need to use virtualisation. Perhaps Docker on OSX would make this pretty straightforward for your project.

@roryrjb Thanks for the response. Tried installing it with docker and it worked !
