### ISSUE TITLE
RFE: new release?

### ISSUE THREAD

**Issue by giuseppe** [seccomp/libseccomp#177]
the Docker default seccomp profile changed to include io_uring_* syscalls.

It doesn't work with the last released version of libseccomp since it lacks the definition for these syscalls.

The issue is already resolved on master, could it be possible to tag a new release?

**Comment by drakenclimber** [comment]
Yes, we are in the process of a v2.4.2 libseccomp release.  I don't have a timeframe yet, but it should be in the next few weeks.

Thanks!
