### ISSUE TITLE
BUG: tests/15-basic-resolver shouldn't use __NR_open on aarch64

### ISSUE THREAD

**Issue by atsampson** [seccomp/libseccomp#184]
Building libseccomp 2.4.2 against the headers from Linux 5.3.9 on aarch64 fails because `__NR_open` isn't defined (since [this commit](https://github.com/torvalds/linux/commit/a0673fdbcd42105261646cd4f3447455b5854a32), I think):

```
15-basic-resolver.c: In function ‘main’:
15-basic-resolver.c:58:46: error: ‘__NR_open’ undeclared (first use in this function)
```

I've worked around this by wrapping lines 58-59 with `#ifdef __NR_open`, but perhaps it might be better to test with a different syscall there?

**Comment by pcmoore** [comment]
I ran into this problem too, and I have a fix (use __SNR instead of __NR), but I'm traveling now and won't be able to submit the PR until Monday.  The good news is that this only affects the test, the library is working as it should.

**Comment by pcmoore** [comment]
I'm sorry, I already submitted this fix as part of PR #182 ... oops!

**Comment by pcmoore** [comment]
@atsampson is this working for you now with the master branch?  I think it should be resolved (and I'd like to close this issue), but I wanted to check with you first.

**Comment by atsampson** [comment]
Yes - I can confirm that the tests work fine for me now on both amd64 and aarch64. Thanks very much!

**Comment by pcmoore** [comment]
Great, thanks for the confirmation!
