### ISSUE TITLE
Posting to mailing list without Google account?

### ISSUE THREAD

**Issue by oxr463** [seccomp/libseccomp#189]
How can I post to the mailing list without a Google account? Perhaps this can be added to <https://github.com/seccomp/libseccomp/blob/master/CONTRIBUTING.md#email-your-patches>.

**Comment by drakenclimber** [comment]
It's a standard email mailing list and anyone with an email address can post to it.  I often post to it from my work email - which is definitely not gmail :).

In the to: or cc: field simply add `libseccomp@googlegroups.com`

**Comment by pcmoore** [comment]
It's also worth mentioning that a Google account is not necessary to join the mailing list.  From the README.md (emphasis added):

> The project mailing list is currently hosted on Google Groups at the URL below, **please note that a Google account is not required to subscribe to the mailing list**.
> 
> https://groups.google.com/forum/#!forum/libseccomp
> https://groups.google.com/forum/#!forum/libseccomp/join

**Comment by oxr463** [comment]
Ah okay, thank you. I entered my email and the one that it sent asked me to login via Google.

**Comment by pcmoore** [comment]
Further, you can always submit your patches as a GitHub PR.  To be honest that is the way most people submit patches to the project these days.
