### ISSUE TITLE
RFE: sys/prctl.h should not be included when using musl

### ISSUE THREAD

**Issue by anarchpenguin** [seccomp/libseccomp#19]
make -j5 --no-print-directory 
make --quiet --no-print-directory all-recursive
Making all in include
Making all in src
Making all in .
In file included from /var/tmp/tmpfs/portage/sys-libs/libseccomp-2.2.3/work/libseccomp-2.2.3/src/system.h:26:0,
                 from /var/tmp/tmpfs/portage/sys-libs/libseccomp-2.2.3/work/libseccomp-2.2.3/src/arch.h:31,
                 from /var/tmp/tmpfs/portage/sys-libs/libseccomp-2.2.3/work/libseccomp-2.2.3/src/db.h:30,
                 from /var/tmp/tmpfs/portage/sys-libs/libseccomp-2.2.3/work/libseccomp-2.2.3/src/system.c:28:
/usr/include/linux/prctl.h:133:8: error: redefinition of ‘struct prctl_mm_map’
 struct prctl_mm_map {
        ^
In file included from /var/tmp/tmpfs/portage/sys-libs/libseccomp-2.2.3/work/libseccomp-2.2.3/src/system.c:24:0:
/usr/include/sys/prctl.h:88:8: note: originally defined here
 struct prctl_mm_map {
        ^
Makefile:642: recipe for target 'libseccomp_la-system.lo' failed

**Comment by pcmoore** [comment]
For reference: http://www.musl-libc.org

**Comment by pcmoore** [comment]
See related pull request from @somasis https://github.com/seccomp/libseccomp/pull/23

**Comment by pcmoore** [comment]
I believe this should be fixed with faf6919f36eae556f1d4e40b8847070221f553c6, please try it and let me know if it works (or doesn't work) for you.

**Comment by pcmoore** [comment]
@anarchpenguin @somasis can either of you verify this fix?

**Comment by somasis** [comment]
Sorry for not responding sooner, it slipped my mind. Yes, this works fine.

**Comment by pcmoore** [comment]
Great, thanks for your help!
