### ISSUE TITLE
RFE: seccomp() syscall and TSYNC flag support never configured

### ISSUE THREAD

**Issue by justincormack** [seccomp/libseccomp#20]
Currently the tsync support is wrapped with HAVE_SECCOMP but there is actually no configure test, perhaps as no existing libc has the seccomp call available.

However it would be perfectly normal to just call seccomp(2) with syscall() as glibc policy seems to be mostly not to expose specialist syscalls at all.

In which case the library could attempt to use syscall(SYS_seccomp, ...) if tsync was set, and fail the filter load if not, rather than just having a tsync option which is not usable even if supported by the kernel.

This behaviour would seem more useful as tsync support is quite widespread, and it is important for many applications. Otherwise the Go libseccomp wrapper should have a warning saying always use `runtime.LockOSThread()` if you use this library or filtering may not be applied to the calls you expect.

**Comment by pcmoore** [comment]
As noted in the autoconfigure script, this functionality was added but disabled pending further testing.

**Comment by pcmoore** [comment]
I've enabled the seccomp() syscall, a thread sync as a result, in a1f144a9a28aa1b831f7d3f481fb3e0e5e3de3aa, but additional testing is needed on the different platforms due to the nature of the implementation.

**Comment by pcmoore** [comment]
See commit 08a682a9f895b8f622499df5ee69fcabe1e3cbab.  We've had enough testing that I'm reasonably confident in considering this issue resolved.
