### ISSUE TITLE
BUG: tests fail x86 due to direct wired socket syscalls on Linux 4.3

### ISSUE THREAD

**Issue by andreas-schwab** [seccomp/libseccomp#21]
test mode:  c
 test type:  bpf-valgrind
 batch name: 15-basic-resolver
 test mode:  c
 test type:  basic
Test 15-basic-resolver%%001-00001 result:   FAILURE 15-basic-resolver rc=1
 batch name: 16-sim-arch_basic
 test mode:  c
 test type:  bpf-sim
 test arch:  x86
Test 16-sim-arch_basic%%001-00001 result:   ERROR 16-sim-arch_basic rc=14
 test arch:  x86
Test 16-sim-arch_basic%%002-00001 result:   ERROR 16-sim-arch_basic rc=14
 test arch:  x86
Test 16-sim-arch_basic%%003-00001 result:   ERROR 16-sim-arch_basic rc=14
 test arch:  x86
Test 16-sim-arch_basic%%004-00001 result:   ERROR 16-sim-arch_basic rc=14
 test arch:  x86
Test 16-sim-arch_basic%%005-00001 result:   ERROR 16-sim-arch_basic rc=14
 test arch:  x86
Test 16-sim-arch_basic%%006-00001 result:   ERROR 16-sim-arch_basic rc=14
Test 16-sim-arch_basic%%007-00001 result:   ERROR 16-sim-arch_basic rc=14
Test 16-sim-arch_basic%%008-00001 result:   ERROR 16-sim-arch_basic rc=14
Test 16-sim-arch_basic%%009-00001 result:   ERROR 16-sim-arch_basic rc=14
Test 16-sim-arch_basic%%010-00001 result:   ERROR 16-sim-arch_basic rc=14
Test 16-sim-arch_basic%%011-00001 result:   ERROR 16-sim-arch_basic rc=14
Test 16-sim-arch_basic%%012-00001 result:   ERROR 16-sim-arch_basic rc=14
 test mode:  c
 test type:  bpf-valgrind
 batch name: 17-sim-arch_merge
 test mode:  c
 test type:  bpf-sim
Test 17-sim-arch_merge%%001-00001 result:   ERROR 17-sim-arch_merge rc=14
Test 17-sim-arch_merge%%002-00001 result:   ERROR 17-sim-arch_merge rc=14
Test 17-sim-arch_merge%%003-00001 result:   ERROR 17-sim-arch_merge rc=14
Test 17-sim-arch_merge%%004-00001 result:   ERROR 17-sim-arch_merge rc=14
Test 17-sim-arch_merge%%005-00001 result:   ERROR 17-sim-arch_merge rc=14
Test 17-sim-arch_merge%%006-00001 result:   ERROR 17-sim-arch_merge rc=14
Test 17-sim-arch_merge%%007-00001 result:   ERROR 17-sim-arch_merge rc=14
Test 17-sim-arch_merge%%008-00001 result:   ERROR 17-sim-arch_merge rc=14
Test 17-sim-arch_merge%%009-00001 result:   ERROR 17-sim-arch_merge rc=14

**Comment by pcmoore** [comment]
This appears due to changes in Linux 4.3 which enabled direct access to the socket syscalls, see Andy's commit:

    commit 9dea5dc921b5f4045a18c63eb92e84dc274d17eb
    Author: Andy Lutomirski <luto@kernel.org>
    Date:   Tue Jul 14 15:24:24 2015 -0700

    x86/entry/syscalls: Wire up 32-bit direct socket calls
    
    On x86_64, there's no socketcall syscall; instead all of the
    socket calls are real syscalls.  For 32-bit programs, we're
    stuck offering the socketcall syscall, but it would be nice to
    expose the direct calls as well.  This will enable seccomp to
    filter socket calls (for new userspace only, but that's fine for
    some applications) and it will provide a tiny performance boost.
    
    Signed-off-by: Andy Lutomirski <luto@kernel.org>
    Cc: Alexander Larsson <alexl@redhat.com>
    Cc: Andy Lutomirski <luto@amacapital.net>
    Cc: Cosimo Cecchi <cosimo@endlessm.com>
    Cc: Dan Nicholson <nicholson@endlessm.com>
    Cc: Linus Torvalds <torvalds@linux-foundation.org>
    Cc: Peter Zijlstra <peterz@infradead.org>
    Cc: Rajalakshmi Srinivasaraghavan <raji@linux.vnet.ibm.com>
    Cc: Thomas Gleixner <tglx@linutronix.de>
    Cc: Tulio Magno Quites Machado Filho <tuliom@linux.vnet.ibm.com>
    Cc: libc-alpha <libc-alpha@sourceware.org>
    Link: http://lkml.kernel.org/r/cb5138299d37d5800e2d135b01a7667fa6115854.1436912629.git.luto@kernel.org
    Signed-off-by: Ingo Molnar <mingo@kernel.org>

**Comment by pcmoore** [comment]
This should be resolved with 983835f3e0fd000a42c8beaea9d7fbe726ffff65.
