### ISSUE TITLE
Q: why do libseccomp-2.4.3.tar.gz differ

### ISSUE THREAD

**Issue by Albert1st1** [seccomp/libseccomp#220]
If i download libseccomp-2.4.3.tar.gz from releases or archive why do they differ.
If i check sha256sum the files differ.
https://github.com/seccomp/libseccomp/releases/download/v2.4.3/libseccomp-2.4.3.tar.gz
cf15d1421997fac45b936515af61d209c4fd788af11005d212b3d0fd71e7991d

https://github.com/seccomp/libseccomp/archive/v2.4.3/libseccomp-2.4.3.tar.gz
4d86f0bd0847795bf7f7bf6e44cb73edf4417d84f6d8848c23eda99b0c50fce6

**Comment by pcmoore** [comment]
Hi @Albert1st1, unfortunately the GH archive links are dynamically created by GH and the checksums are known to change from time to time; if you do a search on this problem you will see several projects that have similar problems.

This is one of the many reasons why we create our own tarballs and include them as part of the release.  The tarballs we provide are *not* dynamically generated, they are generated once at release time.

**Comment by Albert1st1** [comment]
@pcmoore  Thank you very much for the explanation.
