### ISSUE TITLE
BUG: use syscall getrlimit error on aarch64

### ISSUE THREAD

**Issue by Kangenbo** [seccomp/libseccomp#234]
I have trouble when using getrlimit in libseccomp-v2.4.3. It's a EPERM error. 
I use strace to track the error as follow:

`getrlimit(RLIMIT_NOFILE,****` 0xffffe2df4370) = -1 EPERM (Operation not permitted)

The linux kernel i use is 4.19 and i find a commits which update the internal syscall tables to Linux v5.4-rc4[https://github.com/seccomp/libseccomp/commit/bf747eb21e428c2b3ead6ebcca27951b681963a0](url)

So libseccomp do not support linux kernel 4.19 any more?

**Comment by drakenclimber** [comment]
> The linux kernel i use is 4.19 and i find a commits which update the internal syscall tables to Linux v5.4-rc4https://github.com/seccomp/libseccomp/commit/bf747eb21e428c2b3ead6ebcca27951b681963a0

That commit (link above was incorrect, by the way - here's the [correct link](https://github.com/seccomp/libseccomp/commit/bf747eb21e428c2b3ead6ebcca27951b681963a0)) added support for syscalls that were added in the v5.4-rc4 kernel.  Linux goes out of its way to ensure a consistent API and backward compatibility, so this commit should have no effect on older kernels.

I would expect v2.4.3 of libseccomp to work properly on kernel 4.19.

Can you please share your libseccomp filter code?

**Comment by Kangenbo** [comment]
Sorry the link is incorrect...For the correct link, there is a change about getrlimit
![image](https://user-images.githubusercontent.com/33171553/81462133-e216c180-91e2-11ea-96fa-d33e3b1fb57b.png)
If i return it back, use { "getrlimit", 163 }, the error will be fixed. Is this change correct?

**Comment by drakenclimber** [comment]
Are you on arm64 perhaps?
https://bugs.launchpad.net/ubuntu/+source/libseccomp/+bug/1877633
https://github.com/seccomp/libseccomp/pull/235#issuecomment-626479305

**Comment by Kangenbo** [comment]
Yes！the same problem, it can be fixed by alexmurray's commits. Will you merge it to master?

**Comment by drakenclimber** [comment]
Awesome!  Yes, we'll definitely resolve @alexmurray's issue.  I will review the patchset soon.

Thanks for the bug report.

**Comment by pcmoore** [comment]
Actually, let's unlink issue #235 and use this for the v2.4.4 milestone.

**Comment by pcmoore** [comment]
> Actually, let's unlink issue #235 and use this for the v2.4.4 milestone.

Correction, #224 is a PR not an issue (GH treats them mostly the same).  The reason for unlinking that PR is that it is for the master branch and will not apply cleanly to the v2.4.x release branch; a separate v2.4.x specific patch will need to be developed.

**Comment by drakenclimber** [comment]
Good call.

**Comment by Kangenbo** [comment]
Nice. Thanks for your help, looking forward to seeing v2.4.4

**Comment by drakenclimber** [comment]
I committed the fix for this bug to the v2.4 release branch in this commit https://github.com/seccomp/libseccomp/commit/70d4916082a1d3a1ddef4e858be30cff6bbbb123.  @Kangenbo let me know if have any other issues.

This patch will be available in the upcoming [v2.4.4](https://github.com/seccomp/libseccomp/milestone/9) release.
