### ISSUE TITLE
BUG: the seccomp_attr_get/set(3) manpages do not document SCMP_FLTATR_CTL_OPTIMIZE

### ISSUE THREAD

**Issue by pcmoore** [seccomp/libseccomp#245]
Not much to say beyond the subject line.  @drakenclimber do you want to take this one?

**Comment by drakenclimber** [comment]
Sure

**Comment by pcmoore** [comment]
Ping - I just wanted to make sure you didn't forget about this one @drakenclimber :)

**Comment by drakenclimber** [comment]
Yep, I should be able to get to it this week.  But thanks for the reminder; I can use all the help I can get these days :)

**Comment by pcmoore** [comment]
Closed via PR #266.
