### ISSUE TITLE
Q: what are pseudo syscalls?

### ISSUE THREAD

**Issue by vt-alt** [seccomp/libseccomp#249]
There are two syscalls for x86 with are essentially the same differing only in output buffer. That is `newfstatat` and `fstatat64`.

I'd expect if I set a rule for either of these names with `seccomp_arch_add` (inexact rule) correct syscalls would be handled for appropriate arches.

But what is actually happening is quite puzzling.

When I set a rule (for native and x86 arch) for `fstatat64` pfc looks like this:
```
#
# pseudo filter code start
#
# filter for arch x86_64 (3221225534)
if ($arch == 3221225534)
  # filter for syscall "fstatat64" (4294957285) [priority: 65533]
  if ($syscall == 4294957285)
    if ($a2.hi32 & 0x00000000 == 0)
      if ($a2.lo32 & 0x00008000 == 32768)
        action ERRNO(1);
  # default action
  action ALLOW;
# filter for arch x86 (1073741827)
if ($arch == 1073741827)
  # filter for syscall "fstatat64" (300) [priority: 65534]
  if ($syscall == 300)
    if ($a2 & 0x00008000 == 32768)
      action ERRNO(1);
  # default action
  action ALLOW;
# invalid architecture action
action KILL;
#
# pseudo filter code end
#
```
Why it checks for 4294957285 (which is -10011) for x86_64?

When I set a rule for `newfstatat` pfc is:
```
#
# pseudo filter code start
#
# filter for arch x86_64 (3221225534)
if ($arch == 3221225534)
  # filter for syscall "newfstatat" (262) [priority: 65533]
  if ($syscall == 262)
    if ($a2.hi32 & 0x00000000 == 0)
      if ($a2.lo32 & 0x00008000 == 32768)
        action ERRNO(1);
  # default action
  action ALLOW;
# filter for arch x86 (1073741827)
if ($arch == 1073741827)
  # default action
  action ALLOW;
# invalid architecture action
action KILL;
#
# pseudo filter code end
#
```
There is just no check for x86.

**Comment by pcmoore** [comment]
Hi @vt-alt.  The quick answer is that the negative pseudo-syscalls are placeholder syscalls for architectures/ABIs which do not support that particular syscall (some syscalls are not common across all ABIs on Linux).

For example, in the `fstatat64()` case, the syscall is defined on 32-bit x86 (syscall number 300) but it is not defined on 64-bit x86_64.  The opposite is true for the `newfsatat()` syscall where it is undefined for 32-bit x86 but defined on 64-bit x86_64 (syscall number 262).

I'm going to close this issue, but if you have any additional question on this please feel free to comment.

**Comment by vt-alt** [comment]
There are two questions.

1. Why check for non-existent syscall 4294957285 in actually generated bpf?
This would impact performance. On x86 there is no such check for pseudo syscall.
Also, `seccomp_rule_add` reported success installing `fstatat64` on x86_64. This would give a false sense of security if people not actually check generated bpf code.

2. Why not alias `newfstatat` and `fstatat64`? They are semantically the same.
Why I ask the second question? `libseccomp` proposing the benefit of aliasing syscalls on different architectures. But not in cases like this.
If a person comes from x86 she may not know that there is `newfstatat` for the same functionality as `fstatat64`. So, that proposed architectural independence is really could be misunderstood.

**Comment by pcmoore** [comment]
> Why check for non-existent syscall 4294957285 in actually generated bpf?

We shouldn't, and we didn't used to do that, but it looks like current libseccomp has a bug here.

> Why not alias newfstatat and fstatat64?

We've considered adding an abstraction layer on top of the core libseccomp filtering API, but there are higher priority items.

**Comment by pcmoore** [comment]
> We shouldn't, and we didn't used to do that, but it looks like current libseccomp has a bug here.

Thanks for reporting this @vt-alt, I've created a new issue #252 to track this problem, feel free to follow that issue for updates.
