### ISSUE TITLE
RFE: update syscall tables to 4.5-rc3 (or later)

### ISSUE THREAD

**Issue by pcmoore** [seccomp/libseccomp#25]
We want the most current syscall list at the time of release.

**Comment by pcmoore** [comment]
Fixed in commit 173b96ba8d36a4b1954e99570e82f2f932fe056a.

**Comment by dalu** [comment]
Is there a minimum kernel headers version necessary to build/use libseccomp 2.3.0?
Could I use it with Kernel 3.18.x?

**Comment by pcmoore** [comment]
It wouldn't make much sense to build and/or use libseccomp on Linux Kernel's earlier than v3.5 (the first version where seccomp mode 2 was available) but other than that restriction, no, you should be able to build and use libseccomp regardless of the kernel version.

If you run into problems on a specific kernel version let us know as I would consider that a bug.

**Comment by dalu** [comment]
Thank you :)
Apparently this with 2.2.0: https://bugs.gentoo.org/show_bug.cgi?id=551248

I had no problems so far compiling 2.3.0 with 3.18.27 kernel.

**Comment by pcmoore** [comment]
Great, thanks for letting us know.
