### ISSUE TITLE
BUG: rename the "master" branch to "main"

### ISSUE THREAD

**Issue by pcmoore** [seccomp/libseccomp#255]
Similar to [PR #246](https://github.com/seccomp/libseccomp/pull/246) we need to change the name of the "master" branch to "main", or similar.  This is quite easy, and via a branch rename, it can be done without losing any of the git history; there is no good reason to *not* do this.

The steps are simple:
1. Rename the local git repostory: `git branch -m master main`
2. Push the "main" branch to GitHub: `git push origin main`
3. Switch the default branch on GitHub to "main" (see Settings -> Branches)
4. Merge any outstanding PRs against "master" into "main"
5. Update the badges in README.md to reference the "main" branch
6. Once all PR's referencing "master" have been merged, delete the "master" branch: `git push origin :master`

**Comment by pcmoore** [comment]
It looks like GH is working on a way to rename the master branch without disrupting issues/PRs (see link below).  Considering the timeline it may be easier to wait for GH to roll out the renaming support.
* https://github.com/github/renaming

**Comment by pcmoore** [comment]
GitHub now supports renaming branches, see below:

* https://github.blog/changelog/2021-01-19-support-for-renaming-an-existing-branch

This looks like it should be seamless, what do you think @drakenclimber, any objections to me making the change now?

**Comment by drakenclimber** [comment]
Cool!  I was hoping they would automate away most of the pain.  This looks great.

Let's do it!

**Comment by pcmoore** [comment]
Okay, the rename is done and I pushed a small commit with updates to the README.md (point the badges at the new branch) for the main, release-2.5, and release-2.4 branches (everything else is unsupported at this point).

I'm going to close this issue as I think we are done, but if anyone notices anything wrong with the rename please drop a comment below and we'll work on fixing it up.

**Comment by drakenclimber** [comment]
Thanks, @pcmoore!
