### ISSUE TITLE
Q: when will master branch with RISCV support be added to a release?

### ISSUE THREAD

**Issue by mxaddict** [seccomp/libseccomp#262]
[Question] When will master branch with RISCV support be added to a release?

**Comment by mxaddict** [comment]
I see that parisc is listed as support, but I can't seem to compile for riscv64 on the master branch or the latest tagged release.

**Comment by pcmoore** [comment]
> When will master branch with RISCV support be added to a release?

It will be included in the v2.5.0 release which you can track using the [v2.5.0 milestone](https://github.com/seccomp/libseccomp/milestone/4).  We are working hard to get this release out as soon as possible.

> ... I can't seem to compile for riscv64 on the master branch or the latest tagged release.

It should work using the master branch, can you go into more detail about the problems you are having?

**Comment by mxaddict** [comment]
I just double checked and it does work with master, I was trying it with the latest tag when it did not work.

**Comment by mxaddict** [comment]
Thanks for the info

**Comment by pcmoore** [comment]
No problem, glad to hear you got it working.
