### ISSUE TITLE
RFE: add support for the SuperH 32-bit ABI

### ISSUE THREAD

**Issue by pcmoore** [seccomp/libseccomp#272]
As mentioned by @glaubitz in PR #271, the SuperH ABI is still being developed as part of the [J-Core](https://j-core.org) project.  Once the necessary kernel support has been implemented in Linus' tree we can look into adding support to libseccomp with the help of @glaubitz and other SuperH/J-Core developers.

**Comment by pcmoore** [comment]
From @glaubitz:
> @pcmoore We have implemented SECCOMP_FILTER for SH now, it will be posted shortly to the LKML. Hope to be able to get it merged for 5.9.

That's good news, please keep us updated @glaubitz.

**Comment by dm0-** [comment]
Looks like this is in v5.9-rc1: https://github.com/torvalds/linux/commit/0bb605c2c7f2b4b314b91510810b226de7f34fa1

**Comment by pcmoore** [comment]
> Looks like this is in v5.9-rc1: [torvalds/linux@0bb605c](https://github.com/torvalds/linux/commit/0bb605c2c7f2b4b314b91510810b226de7f34fa1)

... and there is a new PR from @glaubitz with the libseccomp support :)

@drakenclimber need to get new releases out for the v2.4.x and v2.5.x release streams, but this is definitely something we want to get in for v2.6.0.

**Comment by pcmoore** [comment]
This was resolved in #285.
