### ISSUE TITLE
BUG: pseudo-syscalls not working correctly on x32

### ISSUE THREAD

**Issue by hvdijk** [seccomp/libseccomp#282]
Commit 9b129c41ac1f43d373742697aa2faf6040b9dfab introduces the concept of "syscall munging" to subtract some base number from syscall numbers to make it easier to use them as an offset into a table. Despite messages in this commit specifically addressing negative pseudo syscall numbers, this does not actually handle negative pseudo syscall numbers properly, which shows up as a test failure in 29-sim-pseudo_syscall for at least x32 and probably all architectures that use munging.

29-sim-pseudo_syscall does `rc = seccomp_rule_add(ctx, SCMP_ACT_KILL, SCMP_SYS(sysmips), 0);`, which passes `__PNR_sysmips` as `syscall`. This syscall remains unmodified until `_db_col_rule_add` calls `arch_filter_rule_add`, which calls `arch_syscall_translate`, which calls `arch_syscall_resolve_num`. For x32, this resolves to a call to `x32_syscall_resolve_num_munge`, which unconditionally subtracts `X32_SYSCALL_BIT` and then calls `x32_syscall_resolve_num`. However, `x32_syscall_resolve_num` is only set up to handle `__PNR_sysmips`, not `__PNR_sysmips - X32_SYSCALL_BIT`! In order to get this test to pass after this commit, it would somehow need to know that it needs to add `X32_SYSCALL_BIT` to the syscall number, but that it unreasonable, the whole point of these pseudo-syscalls is to be able to write the same code across all architectures regardless of which syscalls are actually supported.

If syscall numbers can never be negative for any architecture, it is possible to fix this problem by changing all the munging/unmunging routines to leave negative numbers alone: they must be pseudo syscall numbers. This works for x32, but I do not have enough information to say whether this is safe for all architectures. (Edit: it would also require some special handling to prevent an invalid syscall number from becoming a valid pseudo-syscall number by the subtraction of `X32_SYSCALL_BIT`. Additionally, after 9b129c41ac1f43d373742697aa2faf6040b9dfab, but before v2.5.0, the subtraction has been changed to a bitwise operation which has the same problem: that too can inadvertently treat invalid syscall numbers as valid ones. That should have been kept doing addition and subtraction.)

**Comment by pcmoore** [comment]
Hi @hvdijk, do you have a reproducer that you can share?

**Comment by hvdijk** [comment]
The reproducer is already in the test suite: just do an x32 build and run the test suite's 29-sim-pseudo_syscall test.

**Comment by pcmoore** [comment]
Thanks.

What distribution are you using to test x32?  Is the full distro built natively for x32, or are you building for x32 on x86/x86_64?

**Comment by hvdijk** [comment]
I saw this on a full x32 system (custom, not any distro), but it also shows up when building for x32 on an x86-64 Ubuntu 20.04 system.

**Comment by hvdijk** [comment]
This should show up for mips as well, which does the same type of munging. There's also code for arm that does this munging, but its munging is a noop as long as OABI is unsupported, so it wouldn't actually be a problem there. I have a mips device I can try to test this on but the kernel it's currently running doesn't support seccomp, so it'll take a bit of time before I'm able to confirm it's really a problem there.

**Comment by hvdijk** [comment]
I don't actually see any need for any type of munging since there's nothing preventing the syscall numbers from being stored in the table unmodified. Created a PR with that, the tests pass for x32, but this is untested for MIPS.

**Comment by hvdijk** [comment]
Issue closed. After highly unconstructive feedback I have no wish to continue to help in getting this resolved.

**Comment by pcmoore** [comment]
Reopening as the issue for confirmation and resolution if necessary.

**Comment by hvdijk** [comment]
No. I no longer want to get any messages from you and if you are using this issue, I do. Issue closed again. Leave it closed. Open your own issue if you like but leave me the hell out of it.

**Comment by pcmoore** [comment]
As requested by the reported as part of the delete-tantrum seen above, this issue has been cloned to issue #284.
