### ISSUE TITLE
Q: looking for newer libseccomp package

### ISSUE THREAD

**Issue by stevenhurwitt** [seccomp/libseccomp#297]
Trying to install moby (on a raspberry pi arm64 os), which depends on libseccomp, specifically > 2.4.0. The latest libseccomp2 available is 2.3.3-4. I tried installing 2.4.4 from source but it can't find it. 

What command can I run to find the version of libseccomp and how can I link my "built from source" version with the package manager version?

**Comment by pcmoore** [comment]
Hi @stevenhurwitt.  I'm not familiar with Moby, but you can always grab the latest release tarball from our releases page (below).

* https://github.com/seccomp/libseccomp/releases

**Comment by drakenclimber** [comment]
Depending upon how you installed libseccomp v2.4.4, you may need to tell your system where to find it.  (`sudo make install` usually installs a program to `/usr/local/`.  `/usr/local/` often isn't searched when loading shared libraries.)

There are several ways to add a path to the shared library search, but two of the most common are via the `LD_LIBRARY_PATH` environment variable or using the `/etc/ld.so.conf.d/` configuration files.
