### ISSUE TITLE
detached release version 2.5.1 with missing artifacts

### ISSUE THREAD

**Issue by anthraxx** [seccomp/libseccomp#303]
Hi,
First of all, if you just need more time to finalize the release properly, no worries, I just though after 12 hours I may just ping about some "issues" I have discovered in case that it was unexpected and overlooked. Otherwise sorry for the noise and awaiting the final release :cat: 

- The release tag points to a detached commit that is not part of 1release-2.51 or any other branch:
https://github.com/seccomp/libseccomp/commit/4bf70431a339a2886ab8c82e9a45378f30c6e6c7
GitHub also marks it with `"This commit does not belong to any branch on this respository, and may belong to a fork outside of the repository."`

- It seems like there are no detached signatures uploaded to the GitHub release yet:
https://github.com/seccomp/libseccomp/releases/tag/v2.5.1

Thanks a lot and cheers

**Comment by drakenclimber** [comment]
Thanks for the comment, @anthraxx.  I started the v2.5.1 release yesterday and plan on finishing it up today.  There are a still a few more things I need to do before the v2.5.1 release is fully complete.
