### ISSUE TITLE
Q: build setup difference between libseccomp and libseccomp2?

### ISSUE THREAD

**Issue by OkenKhuman** [seccomp/libseccomp#307]
This may be dumb question but please tell if there is difference between libseccomp and libseccomp2?

What is the difference in build process.

Please clarify my doubt

**Comment by pcmoore** [comment]
Hi @OkenKhuman.

Upstream we don't distinguish between "libseccomp" and "libseccomp2".  My best guess is that your distribution is calling libseccomp v1.x "libseccomp" and libseccomp v2.x "libseccomp2" but I can't be certain.

Regardless, none of the libseccomp v1.x releases are supported by upstream any longer so I would strongly encourage you to upgrade your system to the latest libseccomp release.  As of right now the latest release is libseccomp v2.5.1.  You can find all of the upstream libseccomp releases on this page:

* https://github.com/seccomp/libseccomp/releases

Good luck!
