### ISSUE TITLE
RFE: Use lcov files in Travis CI

### ISSUE THREAD

**Issue by drakenclimber** [seccomp/libseccomp#309]
See this [comment](https://github.com/seccomp/libseccomp/issues/299#issuecomment-737562892) in Issue #299 for more details.

Our current code coverage solution ([cpp-coveralls](https://github.com/eddyxu/cpp-coveralls/blob/master/README.md)) has minor differences from the code coverage results generated from an lcov file.  Initial analysis shows that the lcov file is likely more correct.

Switching from cpp-coveralls to an lcov file will also be beneficial if/when we need to transition from Travis CI to another continuous integration platform.

**Comment by pcmoore** [comment]
I'm closing this issue as it isn't relevant anymore now that we've migrated to GH Actions.
