### ISSUE TITLE
RFE: add documentation note about ppc64le glibc quirks

### ISSUE THREAD

**Issue by drakenclimber** [seccomp/libseccomp#313]
See libseccomp-golang [issue #61](https://github.com/seccomp/libseccomp-golang/issues/61).

When a syscall is blocked via `SCMP_ACT_ERRNO`, glibc on ppc64le is returning that errno as a positive number - and this, thus looks like a valid PID.  (I don't know if other ppc64le syscalls also mishandle errnos.  I'm betting `getppid()` behaves the same.)

Finally, in ppc64le's defense, the man page for `getpid()` says that this function is always successful, so mishandling of error codes is understandable.
```
GETPID(2)                                    Linux Programmer's Manual                                    GETPID(2)

NAME
       getpid, getppid - get process identification
...
ERRORS
       These functions are always successful.
```

**Comment by pcmoore** [comment]
Any progress on this @drakenclimber ?  We're getting *really* close to having all of the v2.5.2 issues resolved so I'm just checking on the few outstanding issues ...

**Comment by drakenclimber** [comment]
I can put together some documentation notes on this issue this afternoon.

**Comment by drakenclimber** [comment]
@pcmoore, hmmm... I'm looking through the doc files right now.  Where do you think would be a good place to put this documentation note?  I don't see a good place for documenting runtime seccomp errors.  My thought is to add something to `seccomp_rule_add.3`, but I'm not enamored with this.

**Comment by drakenclimber** [comment]
I've pushed a swag at resolving this.  Feel free to propose improvements.   Thanks!

**Comment by pcmoore** [comment]
Thanks @drakenclimber, adding it to the `seccomp_rule_add(3)` manpage seems like a good place for right now.  I added a few small comments to your patch, but overall it looks good.

**Comment by drakenclimber** [comment]
Thanks for the comments, @pcmoore.  Good improvements all around.  I've pushed them to pull request #333 333
