### ISSUE TITLE
BUG: Add support for the close_range() syscall

### ISSUE THREAD

**Issue by sswarnas1** [seccomp/libseccomp#316]
Hi,

one of my application is using close_range syscall. when i used libseccomp for hardening, i am getting operation not permitted error for this syscall as the libseccomp 2.4.3 version i am using does not have this support.

can someone suggest how i can handle my case. 

Thank you

**Comment by drakenclimber** [comment]
Looks like `close_range()` made it into the kernel in June 2020 [1].  We'll target adding support for this syscall in the next 2.5.x release.

@sswarnas1 - If you are interested, patchsets are always appreciated :).

[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=278a5fbaed89dacd04e9d052f4594ffd0e0585de

**Comment by brauner** [comment]
On Tue, Feb 16, 2021 at 10:00:15AM -0800, Tom Hromatka wrote:
> Looks like `close_range()` made it into the kernel in June 2020 [1].  We'll target adding support for this syscall in the next 2.5.x release.

And extended with CLOSE_RANGE_CLOEXEC support in 5.11. ;)

**Comment by pcmoore** [comment]
This should be resolve with PR #322 so I'm going to close this out; the fix will be in the next v2.5.x release.
