### ISSUE TITLE
Q: disable SECCOMP_FILTER_FLAG_NEW_LISTENER for a single thread

### ISSUE THREAD

**Issue by grubeli** [seccomp/libseccomp#326]
I enabled SECCOMP_FILTER_FLAG_NEW_LISTENER and works well, is it possible to disable it for a specific thread in a process with tid?

**Comment by pcmoore** [comment]
Do you mean loading a different filter for each thread in a process such that only some filters/threads are subject to supervision by the listener?

Also, a reminder that there is not practical security isolation between threads in a single process.  Using one thread to enforce security policy on another is inherently flawed.

**Comment by grubeli** [comment]
Thanks, yes I'm aware of security flaw in this design but this is environment I work, so I can't change that.

I'm enabling SECCOMP_FILTER_FLAG_NEW_LISTENER  on same process and have handler in a different thread, the handler works well but if I use same syscall inside the handler is causes problems as expected, so what I want is to exclude this specific thread where the handler is located to exclude from intercepting

**Comment by grubeli** [comment]
If have have a thread id before setting BPF filter, maybe it's possible to use BPF to exclude the thread?

**Comment by pcmoore** [comment]
Two things come to mind: first make sure the TSYNC filter attribute is off/0, second make sure that you spawn the supervisor thread *before* you install the filter in the worker thread.  If you load a filter and then spawn a number of threads, all of the newly spawned threads will inherit the filter.

**Comment by grubeli** [comment]
That works, thanks

**Comment by pcmoore** [comment]
Cool, glad that worked for you - good luck!
