### ISSUE TITLE
Q: proper use of the '-b' and '-s' options in the test tool

### ISSUE THREAD

**Issue by Cypresslin** [seccomp/libseccomp#345]
If you try to run one specific test with the tests/regression script with the `-s` flag, it will trigger more tests than you have requested.

This is because the script will loop through all the test files in `run_tests()` and then iterate over their content. The if statement to check for the requested test number `${single_list[@]}` in `run_test_batch()` is incorrect. It's trying to match with the `testnum` which will only increase with non-empty content in a test file. So literally speaking this flag is asking to run the Nth sub-test in each tests.

Move the if statement from `run_test_batch()` to `run_tests()` can solve this issue. I have a [WIP branch](https://github.com/Cypresslin/libseccomp/tree/regression-rework) that can solve this, will submit a MP later.

Example for an attempt to run 13-basic-attrs test:

    $ ./regression -s 13
    =============== Fri Oct 15 13:38:22 UTC 2021 ===============
    Regression Test Report ("regression -s 13")
     batch name: 01-sim-allow
     test mode:  c
     test type:  bpf-sim
     test mode:  c
     test type:  bpf-sim-fuzz
     test mode:  c
     test type:  bpf-valgrind
     batch name: 02-sim-basic
     test mode:  c
     test type:  bpf-sim
     test mode:  c
     test type:  bpf-sim-fuzz
     test mode:  c
     test type:  bpf-valgrind
     batch name: 03-sim-basic_chains
     test mode:  c
     test type:  bpf-sim
     test mode:  c
     test type:  bpf-sim-fuzz
    Test 03-sim-basic_chains%%013-00001 result:   SUCCESS
    Test 03-sim-basic_chains%%013-00002 result:   SUCCESS
    Test 03-sim-basic_chains%%013-00003 result:   SUCCESS
    Test 03-sim-basic_chains%%013-00004 result:   SUCCESS
    Test 03-sim-basic_chains%%013-00005 result:   SUCCESS
     test mode:  c
     test type:  bpf-valgrind
     batch name: 04-sim-multilevel_chains
     test mode:  c
     test type:  bpf-sim
    Test 04-sim-multilevel_chains%%013-00001 result:   SUCCESS
    Test 04-sim-multilevel_chains%%013-00002 result:   SUCCESS
     test mode:  c
     test type:  bpf-sim-fuzz
     test mode:  c
     test type:  bpf-valgrind
     batch name: 05-sim-long_jumps
     test mode:  c
     test type:  bpf-sim
    Test 05-sim-long_jumps%%013-00001 result:   SUCCESS
    Test 05-sim-long_jumps%%013-00002 result:   SUCCESS
    Test 05-sim-long_jumps%%013-00003 result:   SUCCESS
    Test 05-sim-long_jumps%%013-00004 result:   SUCCESS
    Test 05-sim-long_jumps%%013-00005 result:   SUCCESS
     test mode:  c
     test type:  bpf-sim-fuzz
     test mode:  c
     test type:  bpf-valgrind
     batch name: 06-sim-actions
     test mode:  c
     test type:  bpf-sim
    Test 06-sim-actions%%013-00001 result:   SUCCESS
    Test 06-sim-actions%%013-00002 result:   SUCCESS
    Test 06-sim-actions%%013-00003 result:   SUCCESS
    Test 06-sim-actions%%013-00004 result:   SUCCESS
    Test 06-sim-actions%%013-00005 result:   SUCCESS
    Test 06-sim-actions%%013-00006 result:   SUCCESS
    Test 06-sim-actions%%013-00007 result:   SUCCESS
    Test 06-sim-actions%%013-00008 result:   SUCCESS
    Test 06-sim-actions%%013-00009 result:   SUCCESS
    Test 06-sim-actions%%013-00010 result:   SUCCESS
    Test 06-sim-actions%%013-00011 result:   SUCCESS
    Test 06-sim-actions%%013-00012 result:   SUCCESS
    Test 06-sim-actions%%013-00013 result:   SUCCESS
    Test 06-sim-actions%%013-00014 result:   SUCCESS
    Test 06-sim-actions%%013-00015 result:   SUCCESS
    Test 06-sim-actions%%013-00016 result:   SUCCESS
    Test 06-sim-actions%%013-00017 result:   SUCCESS
    Test 06-sim-actions%%013-00018 result:   SUCCESS
    Test 06-sim-actions%%013-00019 result:   SUCCESS
    Test 06-sim-actions%%013-00020 result:   SUCCESS
    Test 06-sim-actions%%013-00021 result:   SUCCESS
    Test 06-sim-actions%%013-00022 result:   SUCCESS
    Test 06-sim-actions%%013-00023 result:   SUCCESS
    Test 06-sim-actions%%013-00024 result:   SUCCESS
    Test 06-sim-actions%%013-00025 result:   SUCCESS
    Test 06-sim-actions%%013-00026 result:   SUCCESS
    Test 06-sim-actions%%013-00027 result:   SUCCESS
    Test 06-sim-actions%%013-00028 result:   SUCCESS
    Test 06-sim-actions%%013-00029 result:   SUCCESS
    Test 06-sim-actions%%013-00030 result:   SUCCESS
    Test 06-sim-actions%%013-00031 result:   SUCCESS
    Test 06-sim-actions%%013-00032 result:   SUCCESS
    Test 06-sim-actions%%013-00033 result:   SUCCESS
    Test 06-sim-actions%%013-00034 result:   SUCCESS
    Test 06-sim-actions%%013-00035 result:   SUCCESS
    Test 06-sim-actions%%013-00036 result:   SUCCESS
    Test 06-sim-actions%%013-00037 result:   SUCCESS
    Test 06-sim-actions%%013-00038 result:   SUCCESS
    Test 06-sim-actions%%013-00039 result:   SUCCESS
    Test 06-sim-actions%%013-00040 result:   SUCCESS
    Test 06-sim-actions%%013-00041 result:   SUCCESS
    Test 06-sim-actions%%013-00042 result:   SUCCESS
    Test 06-sim-actions%%013-00043 result:   SUCCESS
    Test 06-sim-actions%%013-00044 result:   SUCCESS
    Test 06-sim-actions%%013-00045 result:   SUCCESS
    Test 06-sim-actions%%013-00046 result:   SUCCESS
    Test 06-sim-actions%%013-00047 result:   SUCCESS
    Test 06-sim-actions%%013-00048 result:   SUCCESS
    Test 06-sim-actions%%013-00049 result:   SUCCESS
    Test 06-sim-actions%%013-00050 result:   SUCCESS
    Test 06-sim-actions%%013-00051 result:   SUCCESS
    Test 06-sim-actions%%013-00052 result:   SUCCESS
    Test 06-sim-actions%%013-00053 result:   SUCCESS
    Test 06-sim-actions%%013-00054 result:   SUCCESS
    Test 06-sim-actions%%013-00055 result:   SUCCESS
    Test 06-sim-actions%%013-00056 result:   SUCCESS
    Test 06-sim-actions%%013-00057 result:   SUCCESS
    Test 06-sim-actions%%013-00058 result:   SUCCESS
    Test 06-sim-actions%%013-00059 result:   SUCCESS
    Test 06-sim-actions%%013-00060 result:   SUCCESS
    Test 06-sim-actions%%013-00061 result:   SUCCESS
    Test 06-sim-actions%%013-00062 result:   SUCCESS
    Test 06-sim-actions%%013-00063 result:   SUCCESS
    Test 06-sim-actions%%013-00064 result:   SUCCESS
    Test 06-sim-actions%%013-00065 result:   SUCCESS
    Test 06-sim-actions%%013-00066 result:   SUCCESS
    Test 06-sim-actions%%013-00067 result:   SUCCESS
    Test 06-sim-actions%%013-00068 result:   SUCCESS
    Test 06-sim-actions%%013-00069 result:   SUCCESS
    Test 06-sim-actions%%013-00070 result:   SUCCESS
    Test 06-sim-actions%%013-00071 result:   SUCCESS
    Test 06-sim-actions%%013-00072 result:   SUCCESS
    Test 06-sim-actions%%013-00073 result:   SUCCESS
    Test 06-sim-actions%%013-00074 result:   SUCCESS
    Test 06-sim-actions%%013-00075 result:   SUCCESS
    Test 06-sim-actions%%013-00076 result:   SUCCESS
    Test 06-sim-actions%%013-00077 result:   SUCCESS
    Test 06-sim-actions%%013-00078 result:   SUCCESS
    Test 06-sim-actions%%013-00079 result:   SUCCESS
    Test 06-sim-actions%%013-00080 result:   SUCCESS
    Test 06-sim-actions%%013-00081 result:   SUCCESS
    Test 06-sim-actions%%013-00082 result:   SUCCESS
    Test 06-sim-actions%%013-00083 result:   SUCCESS
    Test 06-sim-actions%%013-00084 result:   SUCCESS
    Test 06-sim-actions%%013-00085 result:   SUCCESS
    Test 06-sim-actions%%013-00086 result:   SUCCESS
    Test 06-sim-actions%%013-00087 result:   SUCCESS
    Test 06-sim-actions%%013-00088 result:   SUCCESS
    Test 06-sim-actions%%013-00089 result:   SUCCESS
    Test 06-sim-actions%%013-00090 result:   SUCCESS
    Test 06-sim-actions%%013-00091 result:   SUCCESS
    Test 06-sim-actions%%013-00092 result:   SUCCESS
    Test 06-sim-actions%%013-00093 result:   SUCCESS
    Test 06-sim-actions%%013-00094 result:   SUCCESS
    Test 06-sim-actions%%013-00095 result:   SUCCESS
    Test 06-sim-actions%%013-00096 result:   SUCCESS
    Test 06-sim-actions%%013-00097 result:   SUCCESS
    Test 06-sim-actions%%013-00098 result:   SUCCESS
    Test 06-sim-actions%%013-00099 result:   SUCCESS
    Test 06-sim-actions%%013-00100 result:   SUCCESS
    Test 06-sim-actions%%013-00101 result:   SUCCESS
    Test 06-sim-actions%%013-00102 result:   SUCCESS
    Test 06-sim-actions%%013-00103 result:   SUCCESS
    Test 06-sim-actions%%013-00104 result:   SUCCESS
    Test 06-sim-actions%%013-00105 result:   SUCCESS
    Test 06-sim-actions%%013-00106 result:   SUCCESS
    Test 06-sim-actions%%013-00107 result:   SUCCESS
    Test 06-sim-actions%%013-00108 result:   SUCCESS
    Test 06-sim-actions%%013-00109 result:   SUCCESS
    Test 06-sim-actions%%013-00110 result:   SUCCESS
    Test 06-sim-actions%%013-00111 result:   SUCCESS
    Test 06-sim-actions%%013-00112 result:   SUCCESS
    Test 06-sim-actions%%013-00113 result:   SUCCESS
    Test 06-sim-actions%%013-00114 result:   SUCCESS
    Test 06-sim-actions%%013-00115 result:   SUCCESS
    Test 06-sim-actions%%013-00116 result:   SUCCESS
    Test 06-sim-actions%%013-00117 result:   SUCCESS
    Test 06-sim-actions%%013-00118 result:   SUCCESS
    Test 06-sim-actions%%013-00119 result:   SUCCESS
    Test 06-sim-actions%%013-00120 result:   SUCCESS
    Test 06-sim-actions%%013-00121 result:   SUCCESS
    Test 06-sim-actions%%013-00122 result:   SUCCESS
    Test 06-sim-actions%%013-00123 result:   SUCCESS
    Test 06-sim-actions%%013-00124 result:   SUCCESS
    Test 06-sim-actions%%013-00125 result:   SUCCESS
    Test 06-sim-actions%%013-00126 result:   SUCCESS
    Test 06-sim-actions%%013-00127 result:   SUCCESS
    Test 06-sim-actions%%013-00128 result:   SUCCESS
    Test 06-sim-actions%%013-00129 result:   SUCCESS
    Test 06-sim-actions%%013-00130 result:   SUCCESS
    Test 06-sim-actions%%013-00131 result:   SUCCESS
    Test 06-sim-actions%%013-00132 result:   SUCCESS
    Test 06-sim-actions%%013-00133 result:   SUCCESS
    Test 06-sim-actions%%013-00134 result:   SUCCESS
    Test 06-sim-actions%%013-00135 result:   SUCCESS
    Test 06-sim-actions%%013-00136 result:   SUCCESS
    Test 06-sim-actions%%013-00137 result:   SUCCESS
    Test 06-sim-actions%%013-00138 result:   SUCCESS
    Test 06-sim-actions%%013-00139 result:   SUCCESS
    Test 06-sim-actions%%013-00140 result:   SUCCESS
    Test 06-sim-actions%%013-00141 result:   SUCCESS
    Test 06-sim-actions%%013-00142 result:   SUCCESS
    Test 06-sim-actions%%013-00143 result:   SUCCESS
    Test 06-sim-actions%%013-00144 result:   SUCCESS
    Test 06-sim-actions%%013-00145 result:   SUCCESS
    Test 06-sim-actions%%013-00146 result:   SUCCESS
    Test 06-sim-actions%%013-00147 result:   SUCCESS
    Test 06-sim-actions%%013-00148 result:   SUCCESS
    Test 06-sim-actions%%013-00149 result:   SUCCESS
    Test 06-sim-actions%%013-00150 result:   SUCCESS
    Test 06-sim-actions%%013-00151 result:   SUCCESS
    Test 06-sim-actions%%013-00152 result:   SUCCESS
    Test 06-sim-actions%%013-00153 result:   SUCCESS
    Test 06-sim-actions%%013-00154 result:   SUCCESS
    Test 06-sim-actions%%013-00155 result:   SUCCESS
    Test 06-sim-actions%%013-00156 result:   SUCCESS
    Test 06-sim-actions%%013-00157 result:   SUCCESS
    Test 06-sim-actions%%013-00158 result:   SUCCESS
    Test 06-sim-actions%%013-00159 result:   SUCCESS
    Test 06-sim-actions%%013-00160 result:   SUCCESS
    Test 06-sim-actions%%013-00161 result:   SUCCESS
    Test 06-sim-actions%%013-00162 result:   SUCCESS
    Test 06-sim-actions%%013-00163 result:   SUCCESS
    Test 06-sim-actions%%013-00164 result:   SUCCESS
    Test 06-sim-actions%%013-00165 result:   SUCCESS
    Test 06-sim-actions%%013-00166 result:   SUCCESS
    Test 06-sim-actions%%013-00167 result:   SUCCESS
    Test 06-sim-actions%%013-00168 result:   SUCCESS
    Test 06-sim-actions%%013-00169 result:   SUCCESS
    Test 06-sim-actions%%013-00170 result:   SUCCESS
    Test 06-sim-actions%%013-00171 result:   SUCCESS
    Test 06-sim-actions%%013-00172 result:   SUCCESS
    Test 06-sim-actions%%013-00173 result:   SUCCESS
    Test 06-sim-actions%%013-00174 result:   SUCCESS
    Test 06-sim-actions%%013-00175 result:   SUCCESS
    Test 06-sim-actions%%013-00176 result:   SUCCESS
    Test 06-sim-actions%%013-00177 result:   SUCCESS
    Test 06-sim-actions%%013-00178 result:   SUCCESS
    Test 06-sim-actions%%013-00179 result:   SUCCESS
    Test 06-sim-actions%%013-00180 result:   SUCCESS
    Test 06-sim-actions%%013-00181 result:   SUCCESS
    Test 06-sim-actions%%013-00182 result:   SUCCESS
    Test 06-sim-actions%%013-00183 result:   SUCCESS
    Test 06-sim-actions%%013-00184 result:   SUCCESS
    Test 06-sim-actions%%013-00185 result:   SUCCESS
    Test 06-sim-actions%%013-00186 result:   SUCCESS
    Test 06-sim-actions%%013-00187 result:   SUCCESS
    Test 06-sim-actions%%013-00188 result:   SUCCESS
    Test 06-sim-actions%%013-00189 result:   SUCCESS
    Test 06-sim-actions%%013-00190 result:   SUCCESS
    Test 06-sim-actions%%013-00191 result:   SUCCESS
    Test 06-sim-actions%%013-00192 result:   SUCCESS
    Test 06-sim-actions%%013-00193 result:   SUCCESS
    Test 06-sim-actions%%013-00194 result:   SUCCESS
    Test 06-sim-actions%%013-00195 result:   SUCCESS
    Test 06-sim-actions%%013-00196 result:   SUCCESS
    Test 06-sim-actions%%013-00197 result:   SUCCESS
    Test 06-sim-actions%%013-00198 result:   SUCCESS
    Test 06-sim-actions%%013-00199 result:   SUCCESS
    Test 06-sim-actions%%013-00200 result:   SUCCESS
    Test 06-sim-actions%%013-00201 result:   SUCCESS
    Test 06-sim-actions%%013-00202 result:   SUCCESS
    Test 06-sim-actions%%013-00203 result:   SUCCESS
    Test 06-sim-actions%%013-00204 result:   SUCCESS
    Test 06-sim-actions%%013-00205 result:   SUCCESS
    Test 06-sim-actions%%013-00206 result:   SUCCESS
    Test 06-sim-actions%%013-00207 result:   SUCCESS
    Test 06-sim-actions%%013-00208 result:   SUCCESS
    Test 06-sim-actions%%013-00209 result:   SUCCESS
    Test 06-sim-actions%%013-00210 result:   SUCCESS
    Test 06-sim-actions%%013-00211 result:   SUCCESS
    Test 06-sim-actions%%013-00212 result:   SUCCESS
    Test 06-sim-actions%%013-00213 result:   SUCCESS
    Test 06-sim-actions%%013-00214 result:   SUCCESS
    Test 06-sim-actions%%013-00215 result:   SUCCESS
    Test 06-sim-actions%%013-00216 result:   SUCCESS
    Test 06-sim-actions%%013-00217 result:   SUCCESS
    Test 06-sim-actions%%013-00218 result:   SUCCESS
    Test 06-sim-actions%%013-00219 result:   SUCCESS
    Test 06-sim-actions%%013-00220 result:   SUCCESS
    Test 06-sim-actions%%013-00221 result:   SUCCESS
    Test 06-sim-actions%%013-00222 result:   SUCCESS
    Test 06-sim-actions%%013-00223 result:   SUCCESS
    Test 06-sim-actions%%013-00224 result:   SUCCESS
    Test 06-sim-actions%%013-00225 result:   SUCCESS
    Test 06-sim-actions%%013-00226 result:   SUCCESS
    Test 06-sim-actions%%013-00227 result:   SUCCESS
    Test 06-sim-actions%%013-00228 result:   SUCCESS
    Test 06-sim-actions%%013-00229 result:   SUCCESS
    Test 06-sim-actions%%013-00230 result:   SUCCESS
    Test 06-sim-actions%%013-00231 result:   SUCCESS
    Test 06-sim-actions%%013-00232 result:   SUCCESS
    Test 06-sim-actions%%013-00233 result:   SUCCESS
    Test 06-sim-actions%%013-00234 result:   SUCCESS
    Test 06-sim-actions%%013-00235 result:   SUCCESS
    Test 06-sim-actions%%013-00236 result:   SUCCESS
    Test 06-sim-actions%%013-00237 result:   SUCCESS
    Test 06-sim-actions%%013-00238 result:   SUCCESS
    Test 06-sim-actions%%013-00239 result:   SUCCESS
    Test 06-sim-actions%%013-00240 result:   SUCCESS
    Test 06-sim-actions%%013-00241 result:   SUCCESS
     test mode:  c
     test type:  bpf-sim-fuzz
     test mode:  c
     test type:  bpf-valgrind
     batch name: 07-sim-db_bug_looping
     test mode:  c
     test type:  bpf-sim
     test mode:  c
     test type:  bpf-sim-fuzz
     test mode:  c
     test type:  bpf-valgrind
     batch name: 08-sim-subtree_checks
     test mode:  c
     test type:  bpf-sim
    Test 08-sim-subtree_checks%%013-00001 result:   SUCCESS
    Test 08-sim-subtree_checks%%013-00002 result:   SUCCESS
    Test 08-sim-subtree_checks%%013-00003 result:   SUCCESS
    Test 08-sim-subtree_checks%%013-00004 result:   SUCCESS
    Test 08-sim-subtree_checks%%013-00005 result:   SUCCESS
    Test 08-sim-subtree_checks%%013-00006 result:   SUCCESS
    Test 08-sim-subtree_checks%%013-00007 result:   SUCCESS
    Test 08-sim-subtree_checks%%013-00008 result:   SUCCESS
    Test 08-sim-subtree_checks%%013-00009 result:   SUCCESS
    Test 08-sim-subtree_checks%%013-00010 result:   SUCCESS
    Test 08-sim-subtree_checks%%013-00011 result:   SUCCESS
    Test 08-sim-subtree_checks%%013-00012 result:   SUCCESS
    Test 08-sim-subtree_checks%%013-00013 result:   SUCCESS
    Test 08-sim-subtree_checks%%013-00014 result:   SUCCESS
    Test 08-sim-subtree_checks%%013-00015 result:   SUCCESS
    Test 08-sim-subtree_checks%%013-00016 result:   SUCCESS
    Test 08-sim-subtree_checks%%013-00017 result:   SUCCESS
    Test 08-sim-subtree_checks%%013-00018 result:   SUCCESS
    Test 08-sim-subtree_checks%%013-00019 result:   SUCCESS
    Test 08-sim-subtree_checks%%013-00020 result:   SUCCESS
    Test 08-sim-subtree_checks%%013-00021 result:   SUCCESS
    Test 08-sim-subtree_checks%%013-00022 result:   SUCCESS
    Test 08-sim-subtree_checks%%013-00023 result:   SUCCESS
    Test 08-sim-subtree_checks%%013-00024 result:   SUCCESS
    Test 08-sim-subtree_checks%%013-00025 result:   SUCCESS
    Test 08-sim-subtree_checks%%013-00026 result:   SUCCESS
    Test 08-sim-subtree_checks%%013-00027 result:   SUCCESS
    Test 08-sim-subtree_checks%%013-00028 result:   SUCCESS
    Test 08-sim-subtree_checks%%013-00029 result:   SUCCESS
    Test 08-sim-subtree_checks%%013-00030 result:   SUCCESS
     test mode:  c
     test type:  bpf-sim-fuzz
     test mode:  c
     test type:  bpf-valgrind
     batch name: 09-sim-syscall_priority_pre
     test mode:  c
     test type:  bpf-sim
     test mode:  c
     test type:  bpf-sim-fuzz
     test mode:  c
     test type:  bpf-valgrind
     batch name: 10-sim-syscall_priority_post
     test mode:  c
     test type:  bpf-sim
     test mode:  c
     test type:  bpf-sim-fuzz
     test mode:  c
     test type:  bpf-valgrind
     batch name: 11-basic-basic_errors
     test mode:  c
     test type:  basic
     batch name: 12-sim-basic_masked_ops
     test mode:  c
     test type:  bpf-sim
    Test 12-sim-basic_masked_ops%%013-00001 result:   SUCCESS
    Test 12-sim-basic_masked_ops%%013-00002 result:   SUCCESS
    Test 12-sim-basic_masked_ops%%013-00003 result:   SUCCESS
    Test 12-sim-basic_masked_ops%%013-00004 result:   SUCCESS
    Test 12-sim-basic_masked_ops%%013-00005 result:   SUCCESS
    Test 12-sim-basic_masked_ops%%013-00006 result:   SUCCESS
    Test 12-sim-basic_masked_ops%%013-00007 result:   SUCCESS
    Test 12-sim-basic_masked_ops%%013-00008 result:   SUCCESS
    Test 12-sim-basic_masked_ops%%013-00009 result:   SUCCESS
     test mode:  c
     test type:  bpf-sim-fuzz
     test mode:  c
     test type:  bpf-valgrind
     batch name: 13-basic-attrs
     test mode:  c
     test type:  basic
     batch name: 14-sim-reset
     test mode:  c
     test type:  bpf-sim
     test mode:  c
     test type:  bpf-sim-fuzz
     test mode:  c
     test type:  bpf-valgrind
     batch name: 15-basic-resolver
     test mode:  c
     test type:  basic
     batch name: 16-sim-arch_basic
     test mode:  c
     test type:  bpf-sim
     test mode:  c
     test type:  bpf-valgrind
    Test 16-sim-arch_basic%%013-00001 result:   SUCCESS
     batch name: 17-sim-arch_merge
     test mode:  c
     test type:  bpf-sim
     test mode:  c
     test type:  bpf-valgrind
     batch name: 18-sim-basic_allowlist
     test mode:  c
     test type:  bpf-sim
     test mode:  c
     test type:  bpf-sim-fuzz
    Test 18-sim-basic_allowlist%%013-00001 result:   SUCCESS
    Test 18-sim-basic_allowlist%%013-00002 result:   SUCCESS
    Test 18-sim-basic_allowlist%%013-00003 result:   SUCCESS
    Test 18-sim-basic_allowlist%%013-00004 result:   SUCCESS
    Test 18-sim-basic_allowlist%%013-00005 result:   SUCCESS
     test mode:  c
     test type:  bpf-valgrind
     batch name: 19-sim-missing_syscalls
     test mode:  c
     test type:  bpf-sim
     test mode:  c
     test type:  bpf-valgrind
     batch name: 20-live-basic_die
     test mode:  c
     test type:  live
     batch name: 21-live-basic_allow
     test mode:  c
     test type:  live
     batch name: 22-sim-basic_chains_array
     test mode:  c
     test type:  bpf-sim
     test mode:  c
     test type:  bpf-sim-fuzz
    Test 22-sim-basic_chains_array%%013-00001 result:   SUCCESS
    Test 22-sim-basic_chains_array%%013-00002 result:   SUCCESS
    Test 22-sim-basic_chains_array%%013-00003 result:   SUCCESS
    Test 22-sim-basic_chains_array%%013-00004 result:   SUCCESS
    Test 22-sim-basic_chains_array%%013-00005 result:   SUCCESS
     test mode:  c
     test type:  bpf-valgrind
     batch name: 23-sim-arch_all_le_basic
     test mode:  c
     test type:  bpf-sim
     test mode:  c
     test type:  bpf-valgrind
     batch name: 24-live-arg_allow
     test mode:  c
     test type:  live
     batch name: 25-sim-multilevel_chains_adv
     test mode:  c
     test type:  bpf-sim
     test mode:  c
     test type:  bpf-sim-fuzz
     test mode:  c
     test type:  bpf-valgrind
     batch name: 26-sim-arch_all_be_basic
     test mode:  c
     test type:  bpf-sim
     test mode:  c
     test type:  bpf-valgrind
     batch name: 27-sim-bpf_blk_state
     test mode:  c
     test type:  bpf-sim
     test mode:  c
     test type:  bpf-sim-fuzz
     test mode:  c
     test type:  bpf-valgrind
     batch name: 28-sim-arch_x86
     test mode:  c
     test type:  bpf-sim
     test mode:  c
     test type:  bpf-valgrind
     batch name: 29-sim-pseudo_syscall
     test mode:  c
     test type:  bpf-sim
     test mode:  c
     test type:  bpf-valgrind
     batch name: 30-sim-socket_syscalls
     test mode:  c
     test type:  bpf-sim
    Test 30-sim-socket_syscalls%%013-00001 result:   SUCCESS
     test mode:  c
     test type:  bpf-valgrind
     batch name: 31-basic-version_check
     test mode:  c
     test type:  basic
     batch name: 32-live-tsync_allow
     test mode:  c
     test type:  live
     batch name: 33-sim-socket_syscalls_be
     test mode:  c
     test type:  bpf-sim
     test arch:  s390
    Test 33-sim-socket_syscalls_be%%013-00001 result:   SUCCESS
     test arch:  s390x
    Test 33-sim-socket_syscalls_be%%013-00001 result:   SUCCESS
     test arch:  ppc
    Test 33-sim-socket_syscalls_be%%013-00001 result:   SUCCESS
     test mode:  c
     test type:  bpf-valgrind
     batch name: 34-sim-basic_denylist
     test mode:  c
     test type:  bpf-sim
     test mode:  c
     test type:  bpf-sim-fuzz
    Test 34-sim-basic_denylist%%013-00001 result:   SUCCESS
    Test 34-sim-basic_denylist%%013-00002 result:   SUCCESS
    Test 34-sim-basic_denylist%%013-00003 result:   SUCCESS
    Test 34-sim-basic_denylist%%013-00004 result:   SUCCESS
    Test 34-sim-basic_denylist%%013-00005 result:   SUCCESS
     test mode:  c
     test type:  bpf-valgrind
     batch name: 35-sim-negative_one
     test mode:  c
     test type:  bpf-sim
     test mode:  c
     test type:  bpf-valgrind
     batch name: 36-sim-ipc_syscalls
     test mode:  c
     test type:  bpf-sim
    Test 36-sim-ipc_syscalls%%013-00001 result:   SUCCESS
     test mode:  c
     test type:  bpf-valgrind
     batch name: 37-sim-ipc_syscalls_be
     test mode:  c
     test type:  bpf-sim
     test mode:  c
     test type:  bpf-valgrind
    Test 37-sim-ipc_syscalls_be%%013-00001 result:   SUCCESS
     batch name: 38-basic-pfc_coverage
     test mode:  c
     test type:  basic
     batch name: 39-basic-api_level
     test mode:  c
     test type:  basic
     batch name: 40-sim-log
     test mode:  c
     test type:  bpf-sim
     test mode:  c
     test type:  bpf-sim-fuzz
     test mode:  c
     test type:  bpf-valgrind
     batch name: 41-sim-syscall_priority_arch
     test mode:  c
     test type:  bpf-sim
     test mode:  c
     test type:  bpf-valgrind
     batch name: 42-sim-adv_chains
     test mode:  c
     test type:  bpf-sim
    Test 42-sim-adv_chains%%013-00001 result:   SUCCESS
     test mode:  c
     test type:  bpf-sim-fuzz
     test mode:  c
     test type:  bpf-valgrind
     batch name: 43-sim-a2_order
     test mode:  c
     test type:  bpf-sim
    Test 43-sim-a2_order%%013-00001 result:   SUCCESS
     test mode:  c
     test type:  bpf-valgrind
     batch name: 44-live-a2_order
     test mode:  c
     test type:  live
     batch name: 45-sim-chain_code_coverage
     test mode:  c
     test type:  bpf-sim
     batch name: 46-sim-kill_process
     test mode:  c
     test type:  bpf-sim
     batch name: 47-live-kill_process
     test mode:  c
     test type:  live
     batch name: 48-sim-32b_args
     test mode:  c
     test type:  bpf-sim
    Test 48-sim-32b_args%%013-00001 result:   SUCCESS
     test mode:  c
     test type:  bpf-sim-fuzz
     test mode:  c
     test type:  bpf-valgrind
     batch name: 49-sim-64b_comparisons
     test mode:  c
     test type:  bpf-sim
     test mode:  c
     test type:  bpf-valgrind
     batch name: 50-sim-hash_collision
     test mode:  c
     test type:  bpf-sim
     batch name: 51-live-user_notification
     test mode:  c
     test type:  live
     batch name: 52-basic-load
     test mode:  c
     test type:  basic
     batch name: 53-sim-binary_tree
     test mode:  c
     test type:  bpf-sim
     test arch:  x86_64
    Test 53-sim-binary_tree%%013-00001 result:   SUCCESS
     test arch:  ppc64le
    Test 53-sim-binary_tree%%013-00001 result:   SUCCESS
     test mode:  c
     test type:  bpf-valgrind
     batch name: 54-live-binary_tree
     test mode:  c
     test type:  live
     batch name: 55-basic-pfc_binary_tree
     test mode:  c
     test type:  basic
     batch name: 56-basic-iterate_syscalls
     test mode:  c
     test type:  basic
     batch name: 57-basic-rawsysrc
     test mode:  c
     test type:  basic
     batch name: 58-live-tsync_notify
     test mode:  c
     test type:  live
    Regression Test Summary
     tests run: 319
     tests skipped: 0
     tests passed: 319
     tests failed: 0
     tests errored: 0
    ============================================================

**Comment by pcmoore** [comment]
Hi @Cypresslin,

I could be mistaken, but I think you have confused the '-s' and '-b' options to the 'regression' tool.  The '-b' option allows the user to specify the test (e.g. "02-sim-basic") and the '-s' option allows the caller to specify a specific test line.  For example, if I wanted to only execute the first test in the "02-sim-basic" test I would give the following command:
```
% ./regression -b 02-sim-basic -s 1
=============== Fri Oct 15 03:34:40 PM EDT 2021 ===============
Regression Test Report ("regression -b 02-sim-basic -s 1")
 batch name: 02-sim-basic
 test mode:  c
 test type:  bpf-sim
Test 02-sim-basic%%001-00001 result:   SUCCESS
 test mode:  c
 test type:  bpf-sim-fuzz
 test mode:  c
 test type:  bpf-valgrind
Regression Test Summary
 tests run: 1
 tests skipped: 0
 tests passed: 1
 tests failed: 0
 tests errored: 0
============================================================
```

**Comment by Cypresslin** [comment]
Ah yes,
I got confused by the definition of "batch of tests" and "individual test number".
So this can be closed.
Thanks
