### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by Timmmm** [seccomp/libseccomp#358]
It would go a long way to justifying the "easy to use" claim in the readme if there were examples available. As it stands the raw Linux interface is actually easier to use because I can copy existing examples (e.g. [this one](https://github.com/torvalds/linux/blob/5bfc75d92efd494db37f5c4c173d3639d4772966/samples/seccomp/user-trap.c)).

**Comment by pcmoore** [comment]
> It would go a long way to justifying the "easy to use" claim in the readme ...

That's a bit of an inflammatory comment isn't it?  It's unclear if you are open to suggestions about approaching volunteer and community driven projects with suggestions, but if you are it has been my experience that respect goes much further than the language used above.

Beyond that, and getting back to your suggestion, most (all?) of the manpages include examples and our regression test suite can also be used as a source of code examples for both the native/C and Python libseccomp APIs.

* https://github.com/seccomp/libseccomp/tree/main/doc/man
* https://github.com/seccomp/libseccomp/tree/main/tests

**Comment by drakenclimber** [comment]
I think better and more examples are almost always a good thing.

> I can copy existing examples (e.g. [this one](https://github.com/torvalds/linux/blob/5bfc75d92efd494db37f5c4c173d3639d4772966/samples/seccomp/user-trap.c)).

While that looks easy to copy/paste, it's a lot of code and it has some arcane sections, `BPF_*`, that may be difficult to maintain.

Personally I found libseccomp's [automated tests](https://github.com/seccomp/libseccomp/tree/main/tests) to be a great resource when I was first starting out in the project.  There's an example usage of every major feature in the project.  Perhaps we should advertise this more somehow.
