### ISSUE TITLE
BUG: Python distutils is deprecated

### ISSUE THREAD

**Issue by drakenclimber** [seccomp/libseccomp#372]
On Fedora 35, the following warning is generated when building the Python bindings:
```
./setup.py:26: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
```

**Comment by pcmoore** [comment]
The libcgroup approach looks good to me.  I assume this works on older versions of Python/Cython as well?

**Comment by drakenclimber** [comment]
> The libcgroup approach looks good to me. I assume this works on older versions of Python/Cython as well?

I haven't extensively tested the limits of which python/cython versions are supported, but I do know that it works on Oracle Linux 7 which contains:
```
$ python --version
Python 3.6.8
$ cython --version
Cython version 0.29.28
```
