### ISSUE TITLE
Q: consider dropping the mailing list

### ISSUE THREAD

**Issue by pcmoore** [seccomp/libseccomp#375]
While the mailing list was helpful in the early days of development, now that the project has been on GitHub for several years the mailing list is almost exclusively a spam trap.  I think it may be time to retire the mailing list, but I'd like to hear from others before we make any changes.

*If* we do decide to drop the mailing list I don't think we want to remove it entirely, simply mark it as (effectively) read-only in case anyone wants to refer to it in the future.

**Comment by drakenclimber** [comment]
Sounds good to me.  Obviously we'll need to update the documentation accordingly.

**Comment by pcmoore** [comment]
Okay, I'll start putting things in motion ...

**Comment by pcmoore** [comment]
Update:

* Removed the GH email notification on repo updates
* Updated the mailing list description to point people at the GH repo
* Restricted new subscriptions to an "ask" model 
* Restricted new posts to the group managers

**Comment by drakenclimber** [comment]
This was resolved in commit 3c0dedd45713d7928c459b6523b78f4cfd435269.  Closing this issue
