### ISSUE TITLE
Q: manually setting CFLAGS=-fvisibility=hidden does not work

### ISSUE THREAD

**Issue by LivedForward** [seccomp/libseccomp#403]
when I use CFLAGS=-fvisibility=hidden -fvisibility-inlines-hidden parameters in ./configure command and add this parameters  to configure.ac , it does not work, why?

**Comment by thesamesam** [comment]
You can't generally go around passing this to random projects and expect it to work. You'll need to make sure their symbol versioning is done correctly first.

We also can't really say why if you haven't shared any errors or output.

**Comment by pcmoore** [comment]
We add `-fvisibility=hidden` to the libseccomp CFLAGS in "src/Makefile.am" with all of the API function marked with an `API` macro that is defined at the of "src/api.c".

Reading the GCC wiki on visibility (linked below), I don't believe we gain anything through the use of `-fvisibility-inlines-hidden`, but if I'm wrong about this I would appreciate a pointer/explanation.

* https://gcc.gnu.org/wiki/Visibility

**Comment by pcmoore** [comment]
I'm going to close this issue as I don't believe there is anything for us to do here beyond the comment above, but if you believe there is more to discuss please re-open this issue.
