### ISSUE TITLE
BUG: problems with docker seccomp profiles on ARM

### ISSUE THREAD

**Issue by xiaoge1001** [seccomp/libseccomp#404]
![image](https://user-images.githubusercontent.com/103323735/223421020-c74a40bb-fe0a-4da7-84c6-de80aacd1697.png)
As shown in the above figure，The seccomp configuration does not seem to take effect on the arm machine. Check the status of the corresponding sh process. The seccomp rules should be written. As shown in the following figure:
![image](https://user-images.githubusercontent.com/103323735/223421670-63c070d6-ccbd-475f-9817-3161a935ab1f.png)

**Comment by xiaoge1001** [comment]
But it works well on x86 machines:
![image](https://user-images.githubusercontent.com/103323735/223422474-6238652b-05a1-44f0-ab98-c8afdcfe2de6.png)
![image](https://user-images.githubusercontent.com/103323735/223422702-a04976ae-abd1-478f-ba53-4a064cacdf92.png)

**Comment by xiaoge1001** [comment]
What's the reason for this?

**Comment by pcmoore** [comment]
Hi @xiaoge1001,

Have your brought this up to the Docker folks?  We aren't really in a position to support all of the applications that use libseccomp, e.g. Docker.  If Docker indicates that this is a problem with libseccomp please let us know and we will be happy to dig into this further with you to try and resolve the problem.

**Comment by xiaoge1001** [comment]
The issue has been reported to Docker. The issue link is  https://github.com/moby/moby/issues/45125
