### ISSUE TITLE
Q: new release request

### ISSUE THREAD

**Issue by Zheaoli** [seccomp/libseccomp#417]
For now, the last version is for API v6. The developer need some feature in API  v7 like https://github.com/opencontainers/runc/issues/3860

So, is there any plan to make a new stable release?

**Comment by pcmoore** [comment]
We track our release planning using GH milestones: https://github.com/seccomp/libseccomp/milestones

Also, please see https://github.com/seccomp/libseccomp/issues/406#issuecomment-1723453655
