### ISSUE TITLE
BUG: test 29 is broken on aarch64

### ISSUE THREAD

**Issue by pcmoore** [seccomp/libseccomp#418]
It appears that commit 1852fe3d772914d848907f9d0656747776ed3f98 uncovered an issue on aarch64:

```
% ./regression -m c -T bpf-sim -b 29-sim-pseudo_syscall
=============== Mon Oct 23 04:51:37 PM EDT 2023 ===============
Regression Test Report ("regression -m c -T bpf-sim -b 29-sim-pseudo_syscall")
 batch name: 29-sim-pseudo_syscall
 test mode:  c
 test type:  bpf-sim
bpf-sim
ERROR
Test 29-sim-pseudo_syscall%%001-00001 result:   ERROR bpf_sim rc=8
ERROR
Test 29-sim-pseudo_syscall%%001-00002 result:   ERROR bpf_sim rc=8
ERROR
Test 29-sim-pseudo_syscall%%001-00003 result:   ERROR bpf_sim rc=8
ERROR
Test 29-sim-pseudo_syscall%%001-00004 result:   ERROR bpf_sim rc=8
ERROR
Test 29-sim-pseudo_syscall%%001-00005 result:   ERROR bpf_sim rc=8
ERROR
Test 29-sim-pseudo_syscall%%001-00006 result:   ERROR bpf_sim rc=8
ERROR
Test 29-sim-pseudo_syscall%%001-00007 result:   ERROR bpf_sim rc=8
ERROR
Test 29-sim-pseudo_syscall%%001-00008 result:   ERROR bpf_sim rc=8
ERROR
Test 29-sim-pseudo_syscall%%001-00009 result:   ERROR bpf_sim rc=8
ERROR
Test 29-sim-pseudo_syscall%%001-00010 result:   ERROR bpf_sim rc=8
ERROR
Test 29-sim-pseudo_syscall%%001-00011 result:   ERROR bpf_sim rc=8
bpf-sim
ERROR
Test 29-sim-pseudo_syscall%%002-00001 result:   ERROR bpf_sim rc=8
bpf-sim
ERROR
Test 29-sim-pseudo_syscall%%003-00001 result:   ERROR bpf_sim rc=8
 test mode:  c
 test type:  bpf-valgrind
Regression Test Summary
 tests run: 13
 tests skipped: 0
 tests passed: 0
 tests failed: 0
 tests errored: 13
============================================================
```

**Comment by lixing-star** [comment]
hello, @drakenclimber .
How about to change the condition from 
if (rc == 0)
 to
 if (rc == 0 && (seccomp_arch_native() == SCMP_ARCH_X86))  to filter out the native arch ?
Only arch x86 x86_64 and x32 return rc < 0,  the other arch return rc = 0.

**Comment by pcmoore** [comment]
First off, thanks to everyone who spent time investigating this and thinking about solutions, that was helpful.

I took a look at this today and @drakenclimber's [investigation](https://github.com/seccomp/libseccomp/issues/418#issuecomment-1834243595) seems to have hit at the core problem: the bogus negative syscall number chosen for test 29 isn't actually bogus on a number of systems due to the PNR mapping.  On aarch64 the bogus syscall number maps to a valid pseudo-syscall/PNR, `arch_prctl()` and as @drakenclimber already stated it's a valid syscall on x86.

Considering that test 29 is intended to attempt loading of a *bogus* negative syscall, I think the easiest solution is to choose a negative syscall number well outside the range of the PNR values.  Preliminary testing has shown this to resolve the problem, I'll post a PR shortly.

**Comment by drakenclimber** [comment]
Fixed in commit https://github.com/seccomp/libseccomp/commit/87876aa6ddb7cd70953f120f3d96495c2684ddda.  Thanks everyone for all of the help!
