### ISSUE TITLE
BUG: gcc warning in gen_bpf.c

### ISSUE THREAD

**Issue by drakenclimber** [seccomp/libseccomp#422]
```
gen_bpf.c: In function '_gen_bpf_build_bpf':
gen_bpf.c:2077:21: warning: storing the address of local variable 'pseudo_arch' in '*state.arch' [-Wdangling-pointer=]
 2077 |         state->arch = &pseudo_arch;
      |         ~~~~~~~~~~~~^~~~~~~~~~~~~~
gen_bpf.c:1999:25: note: 'pseudo_arch' declared here
 1999 |         struct arch_def pseudo_arch;
      |                         ^~~~~~~~~~~
gen_bpf.c:1985:49: note: 'state' declared here
 1985 | static int _gen_bpf_build_bpf(struct bpf_state *state,
      |                               ~~~~~~~~~~~~~~~~~~^~~~~
```

**Comment by pcmoore** [comment]
FWIW, I'm not seeing this either with HEAD at 2847f10dddca72167309c04cd09f326fd3b78e2f and GCC v14.2.1, @drakenclimber are you still seeing this warning?

**Comment by drakenclimber** [comment]
> FWIW, I'm not seeing this either with HEAD at [2847f10](https://github.com/seccomp/libseccomp/commit/2847f10dddca72167309c04cd09f326fd3b78e2f) and GCC v14.2.1, @drakenclimber are you still seeing this warning?

Nope.  I really wish I had recorded which GCC I saw this on.  I can't reproduce it currently :(
