### ISSUE TITLE
Q: Is there a next release plan

### ISSUE THREAD

**Issue by huajingyun01** [seccomp/libseccomp#430]
Hi Maintainers,

I have been working on the  [Alpine Linux LoongArch64 port](https://gitlab.alpinelinux.org/alpine/tsc/-/issues/72)  since last year. Unfortunately, the latest release of libseccomp 2.5.5 does not support LoongArch64 yet. We are currently building libseccomp by applying patches for LoongArch64, and have built a lot of packages.

The main branch already supports loongarch64, the first PR: https://github.com/seccomp/libseccomp/pull/356

So, we have been looking forward to the next release of libseccomp. It will be very friendly for package libseccomp for Alpine Linux. I see that historically libseccomp is released once or twice a year. If there is a plan for the next release in the near future?

Thanks!

**Comment by rusty-snake** [comment]
Please search for duplicates before opening new issues. The two top most closed issues already asked the same.

![ResizedImage_2024-06-07_18-02-15_1833](https://github.com/seccomp/libseccomp/assets/41237666/d953ddfd-ff9d-4baa-bda1-9d682de2d3da)

Regarding plans there are [milestones](
https://github.com/seccomp/libseccomp/milestones) and the comments in the other issues.

<sub>Not speak for the libseccomp project.</sub>

**Comment by pcmoore** [comment]
Not much to add beyond what @rusty-snake has already mentioned regarding future libseccomp releases.  I will add that I recently deferred many of the outstanding issues in the v2.6.0 milestone to a later release in the hope of releasing v2.6.0 sooner.

**Comment by huajingyun01** [comment]
> Not much to add beyond what @rusty-snake has already mentioned regarding future libseccomp releases. I will add that I recently deferred many of the outstanding issues in the v2.6.0 milestone to a later release in the hope of releasing v2.6.0 sooner.

Hi, @pcmoore Thank you very much, looking forward to it.
