### ISSUE TITLE
RFE: provide detached signatures of source tarballs

### ISSUE THREAD

**Issue by g4jc** [seccomp/libseccomp#53]
Hello,
First of all thank you for taking the time to sign your hashes! Unfortunately, there is a bit of a problem downstream. Most packaging systems require a GPG signature and the original source file, otherwise they fail. Hence in-line GPG causes a packaging dilemma for maintainers. 
As seen in the following script from a PKGBUILD below:

` |  ==> Making package: libseccomp 2.3.1-1 (Sat Nov  5 09:49:11 EDT 2016)
 |  ==> Retrieving sources...
 |    -> Found libseccomp-2.3.1.tar.gz
 |    -> Found libseccomp-2.3.1.tar.gz.SHA256SUM.asc
 |  ==> Validating source files with sha256sums...
 |      libseccomp-2.3.1.tar.gz ... Passed
 |      libseccomp-2.3.1.tar.gz.SHA256SUM.asc ... Passed
 |  ==> Verifying source file signatures with gpg...
 |      libseccomp-2.3.1.tar.gz.SHA256SUM ... SOURCE FILE NOT FOUND
 |  ==> ERROR: One or more PGP signatures could not be verified!
`

The problem is there is no  libseccomp-2.3.1.tar.gz.SHA256SUM for the packager to download. 

I see two possible ways of fixing this issue, the second being the most proper.

Solution 1) Provide an unsigned libseccomp-2.3.1.tar.gz.SHA256SUM, although this still does not allow one to run validpgpkeys script to verify the source tarball, it does verify the sha256 is correct which could be manually compared with the PKGBUILD creators. (Not optimal)

Solution 2) Consider creating actual detached signatures for your source tarballs as well. Debian is pushing for this good standard and a tutorial for it is available here: https://wiki.debian.org/Creating%20signed%20GitHub%20releases

Thank you for your time.

**Comment by pcmoore** [comment]
Thanks, this is something I'll consider for our future releases.

**Comment by pcmoore** [comment]
I just added a process document for creating new libseccomp releases, RELEASE_PROCESS.md, in commit 4e618d26c58e08b560d0ca894f3381c0dd5d514f and the release process calls for the creation of detached signatures.
