### ISSUE TITLE
RFE: add a list of supported architectures to the README

### ISSUE THREAD

**Issue by vismir2** [seccomp/libseccomp#56]
Please provide a list of supported architectures. As of now it is hard to tell for what types there is already support.

Also please consider supporting the new open source RISC-V architecture in the future

**Comment by pcmoore** [comment]
I do make note of new architectures in the CHANGELOG, but I agree we could probably make it more prominent, e.g. in the README.

If you are interested in RISC-V support, please see the existing PR https://github.com/seccomp/libseccomp/pull/50, there is still work to be done before we can add libseccomp support.  Perhaps you could help that effort?

**Comment by pcmoore** [comment]
Resolved via c14558ec0c8edcd92974adba43543d2d4f20e7f1
