### ISSUE TITLE
Syscall arguments

### ISSUE THREAD

**Issue by sonicou** [seccomp/libseccomp#59]
In many introductions about seccomp it is mentioned that seccomp-bpf programs may not dereference
pointers which constrains all filters to solely evaluating the system call arguments directly.

However in the libseccomp man page there is an example showing just that if I am not mistaken:

```
fd = open("file.txt", 0);

rc = seccomp_rule_add(ctx, SCMP_ACT_ALLOW, SCMP_SYS(read), 3,
			      SCMP_A0(SCMP_CMP_EQ, fd),
			      SCMP_A1(SCMP_CMP_EQ, (scmp_datum_t)buf),
			      SCMP_A2(SCMP_CMP_LE, BUF_SIZE));
	if (rc < 0)
		goto out;

	rc = seccomp_rule_add(ctx, SCMP_ACT_ALLOW, SCMP_SYS(write), 1,
SCMP_CMP(0, SCMP_CMP_EQ, fd));

```

Does this mean that with libseccomp it is possible to filter for specific files and thereby create white and blacklists? And is this safe to use for such purposes?

**Comment by pcmoore** [comment]
In the example above, the filter for the _read()_ syscall is simply examining the pointer as a scalar value, it isn't dereferencing the pointer.

**Comment by sonicou** [comment]
Thanks for explaining.

The question still remaining is whether filtering for specific files like in the example is reliable/secure to build sandboxes.

**Comment by pcmoore** [comment]
That question is beyond the scope of libseccomp.  The libseccomp project provides a easy to use interface to the seccomp-bpf mechanism inside the Linux kernel, it is up to the individual application developers to make use of this functionality.
