### ISSUE TITLE
RFE: new syscalls in Linux 4.9

### ISSUE THREAD

**Issue by rhalet** [seccomp/libseccomp#60]
Some new syscalls will be available in linux 4.9

pkey_alloc
pkey_free
pkey_mprotect

Seems like they will be only available on intel cpus
https://lwn.net/Articles/689395/

I believe libseccomp still needs to adopt to filter those new syscalls

**Comment by justincormack** [comment]
I have done a PR for this #62 - there was also `preadv2` and `pwritev2`

**Comment by pcmoore** [comment]
Fixed via d9102f12fd39bd77151a1f630fcfc8c80f86c55c, but leaving open until we've backported this to a v2.3.x release.

**Comment by pcmoore** [comment]
Commits we want to backport: d9102f12fd39bd77151a1f630fcfc8c80f86c55c e58bfa9032a5e15e2081ddfdda040e7a29de58b9 486c16401ea59657750987b19641d4b8fcc972e2 116b3c1a2e1db53cc35b74f30c080f5265faa674

**Comment by pcmoore** [comment]
Commits backported, closing this out.
