### ISSUE TITLE
RFE: add support for aarch64 big-endian

### ISSUE THREAD

**Issue by pcmoore** [seccomp/libseccomp#66]
The Linux Kernel supports running aarch64 as big-endian (aarch64be?), it would be nice if libseccomp supported this ABI.

* https://groups.google.com/forum/#!topic/libseccomp/H0umHMQiBUQ

**Comment by pcmoore** [comment]
It should be noted that as the time of writing (January 2017) there do not appear to be any major distributions that support aarch64be.

**Comment by michaelweiser** [comment]
FWIW: While not officially supported, I have Gentoo running nicely on armv7veb and aarch64_be. (It's a bit of a hobby of mine.) I'm not running any seccomp'd programs on them though or you likely would have gotten issues and/or PRs already. :)

**Comment by pcmoore** [comment]
Well, at the very least it is good to know that we could stand up a Gentoo aarch64_be system for development/testing.  Although I think I would still need to see a distro/vendor officially support aarch64_be before committing to support it in libseccomp.

**Comment by pcmoore** [comment]
In an effort to keep our outstanding issue list tidy I'm going to close this out because I'm not aware of a mainstream Linux distro providing aarch64_be builds.  Sorry @michaelweiser :/

If someone finds an aarch64_be distro, please let me know and we will reopen this issue!

**Comment by michaelweiser** [comment]
No pressure. :) A BE distro is quite unlikely to happen now because there seems to have been no default-BE ARM hardware since the XScale IXP4xxs and even those are being run LE nowadays.
