### ISSUE TITLE
BUG: matching on uid_t and gid_t arguments on i386 does not work

### ISSUE THREAD

**Issue by mheon** [seccomp/libseccomp#84]
After chasing a bug report to the `libseccomp-golang` bindings (https://github.com/seccomp/libseccomp-golang/issues/24), I think I've found an issue in the library itself.

On 32-bit x86 systems, filters never appear to match arguments of type `uid_t` and `gid_t` when conditionally matching syscalls. Making a filter which blocks calls to `setuid` with argument 0 being equal to 1000, loading it, and then making calling `setuid(1000)` will succeed on x86 (assuming the calling user has permission to `setuid` to that user) but fail on x86-64 after being blocked by the filter. I have verified with several calls that use `uid_t` and `gid_t` arguments (though my testing here is not exhaustive).

Tested on `libseccomp` v2.3.1 on Debian testing (both i386 and x86-64) and Fedora 25 with v2.3.2 (x86-64 only).

Reproducer: https://gist.github.com/mheon/6c558e41c75e45449151f42556c95521

My initial thought is that this might be related to argument size differences in 32-bit and 64-bit kernels. Some digging through the kernel sources indicates it seems to use 16-bit calls, e.g. `setreuid16`, instead of the 32-bit versions used on 64-bit kernels.

**Comment by pcmoore** [comment]
Quick question: have you verified that the 32-bit x86 systems are calling the setuid() syscall and not the setuid32() syscall?  On x86_64 only the setuid() syscall is defined, but both are defined on x86 with glibc calling the setuid32() syscall for setuid() as the x86 setuid() syscall is the older 16-bit version.

I'm guessing that if you add the setuid32() syscall to your reproducer you will find it works as expected, let me know.

**Comment by mheon** [comment]
@pcmoore Looks like that was it - directly calling the 16-bit version of `setuid` triggers the filter, and adding a rule for `setuid32` fixes calls from glibc. Oops.

**Comment by mheon** [comment]
I will note in closing that it's somewhat damaging to portability that `setuid32` can't be added successfully on x86-64, so ensuring that the syscall is blocked successfully requires adding `setuid` and then attempting to add `setuid32` and ignoring it if it fails. I don't know if there's an easy way around this - it might be an unavoidable artifact of the way the kernel grew.

**Comment by pcmoore** [comment]
It should be possible to add setuid32() on x86-64 so long as the seccomp\_*\_exact() variants aren't used to add rules.  Did that not work for you?  If it failed then that is definitely a bug.

**Comment by pcmoore** [comment]
_NOTE: I'm reopening this until we resolve the setuid32() on x86_64 concern raised above_

**Comment by mheon** [comment]
I'll attempt to verify this after lunch. It's entirely possible I made a stupid mistake here (I don't think I was using the exact version of add_rule, but I don't trust my past self enough to say for certain).

**Comment by pcmoore** [comment]
No worries, I'm away from my desk for most of this week so I'm not able to easily verify this myself, I appreciate the help.

**Comment by mheon** [comment]
Spent some time trying to reproduce this today, and was unable to. I was likely using the exact version of rule_add_array before (I also think I might have been storing returned syscall numbers as unsigned which did not help matters). Sorry for the confusion here.
