### ISSUE TITLE
RFE: add support for SECCOMP_RET_KILL_PROCESS

### ISSUE THREAD

**Issue by pcmoore** [seccomp/libseccomp#96]
@kees added support for killing the entire process upstream, as of this moment it has yet to land in Linus' tree, but it will get their eventually.

* https://lkml.org/lkml/2017/8/11/807

**Comment by pcmoore** [comment]
Update: the patch is not upstream, the relevant kernel header files are defined in the commit below.

    commit 0466bdb99e8744bc9befa8d62a317f0fd7fd7421
    Author: Kees Cook
    Date:   Fri Aug 11 13:12:11 2017 -0700

    seccomp: Implement SECCOMP_RET_KILL_PROCESS action
    
    Right now, SECCOMP_RET_KILL_THREAD (neé SECCOMP_RET_KILL) kills the
    current thread. There have been a few requests for this to kill the entire
    process (the thread group). This cannot be just changed (discovered when
    adding coredump support since coredumping kills the entire process)
    because there are userspace programs depending on the thread-kill
    behavior.
    
    Instead, implement SECCOMP_RET_KILL_PROCESS, which is 0x80000000, and can
    be processed as "-1" by the kernel, below the existing RET_KILL that is
    ABI-set to "0". For userspace, SECCOMP_RET_ACTION_FULL is added to expand
    the mask to the signed bit. Old userspace using the SECCOMP_RET_ACTION
    mask will see SECCOMP_RET_KILL_PROCESS as 0 still, but this would only
    be visible when examining the siginfo in a core dump from a RET_KILL_*,
    where it will think it was thread-killed instead of process-killed.
    
    Attempts to introduce this behavior via other ways (filter flags,
    seccomp struct flags, masked RET_DATA bits) all come with weird
    side-effects and baggage. This change preserves the central behavioral
    expectations of the seccomp filter engine without putting too great
    a burden on changes needed in userspace to use the new action.
    
    The new action is discoverable by userspace through either the new
    actions_avail sysctl or through the SECCOMP_GET_ACTION_AVAIL seccomp
    operation. If used without checking for availability, old kernels
    will treat RET_KILL_PROCESS as RET_KILL_THREAD (since the old mask
    will produce RET_KILL_THREAD).
    
    Cc: Paul Moore <paul@paul-moore.com>
    Cc: Fabricio Voznika <fvoznika@google.com>
    Signed-off-by: Kees Cook <keescook@chromium.org>

**Comment by pcmoore** [comment]
See potentially related issue with OpenMP in issue #93.

**Comment by pcmoore** [comment]
See PR #109.

**Comment by drakenclimber** [comment]
@pcmoore, I'll rebase and squash the commits for this PR.  I should be able to get to them this week.  Thanks!

**Comment by pcmoore** [comment]
@drakenclimber that would be helpful thank you.  Please don't feel the need to squash _everything_.  It sounds like you are familiar with upstream kernel development; if you use that as a guideline you should be in good shape.

**Comment by drakenclimber** [comment]
D'oh.  Just saw your comment.  I squashed everything into one commit, but I think I'll split this RFE into two commits - one for the actual code changes and one for the tests.  Thanks.

**Comment by pcmoore** [comment]
Quick update, it looks like support was added back into Linux v4.14.

**Comment by elmarco** [comment]
any update on this feature?

**Comment by pcmoore** [comment]
Sorry @elmarco not yet.

**Comment by drakenclimber** [comment]
@pcmoore - I have rebased the proposed changes on top of the latest master.  Looks like TravisCI was happy with them :)

Let me know if there's anything else you need for this RFE.

[https://github.com/drakenclimber/libseccomp/tree/issues/96-squashed4](https://github.com/drakenclimber/libseccomp/tree/issues/96-squashed4)

**Comment by pcmoore** [comment]
Resolved with PR #130.
